<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capitulo 1 Analisis de la variable objetivo, numericas y categoricas indepentiendes | Analisis exploratorio de datos (EDA)</title>
  <meta name="description" content="Este es un libro creado con bookdown." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capitulo 1 Analisis de la variable objetivo, numericas y categoricas indepentiendes | Analisis exploratorio de datos (EDA)" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este es un libro creado con bookdown." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capitulo 1 Analisis de la variable objetivo, numericas y categoricas indepentiendes | Analisis exploratorio de datos (EDA)" />
  
  <meta name="twitter:description" content="Este es un libro creado con bookdown." />
  

<meta name="author" content="Juan Marín, Santiago Hurtado y Andrés Parejo" />


<meta name="date" content="2025-10-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="análisis-exploratorio-bivariado.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Libro bookdown</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path=""><a href="#introducci%C3%B3n"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="1" data-path="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html"><i class="fa fa-check"></i><b>1</b> Analisis de la variable objetivo, numericas y categoricas indepentiendes</a></li>
<li class="chapter" data-level="2" data-path="01-Marin.html"><a href="#an%C3%A1lisis-exploratorio-bivariado"><i class="fa fa-check"></i><b>2</b> Análisis exploratorio bivariado</a></li>
<li class="chapter" data-level="3" data-path="bivariado-con-variables-categoricas.html"><a href="bivariado-con-variables-categoricas.html"><i class="fa fa-check"></i><b>3</b> Bivariado con variables categoricas</a></li>
<li class="chapter" data-level="4" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>4</b> Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analisis exploratorio de datos (EDA)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Capitulo 1</span> Analisis de la variable objetivo, numericas y categoricas indepentiendes<a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Contexto del conjunto de datos y la situacion sobre la que se va a trabajar</strong></p>
<p>A continuacion se presentan datos asociados a campañas de marketing realizadas por un banco en Portugal. La finalidad de dichas campañas era impulsar la contratacion de depositos a plazo fijo por parte de los clientes afiliados al banco. Los datos abarcan informacion socioeconomica del cliente como detalles a la hora de la interaccion telefonica con el sujeto.
En total se muestran 4521 registros y 17 variables.
Las variables en cuestion junto con su descripcion:
age: Edad del usuario.
job: Profesión del usuario (desempleado, servicios, gestión).
marital: Estado civil del usuario (soltero, casado, divorciado).
education: Nivel educativo del usuario (primaria, secundaria, terciaria).
default: Establece si el cliente tiene crédito en incumplimiento (sí/no).
balance: Saldo promedio anual de la cuenta bancaria.
housing: Establece si posee préstamo hipotecario (sí/no).
loan: Establece si tiene préstamo personal (sí/no).
contact: Tipo de comunicación utilizada (celular o fijo).
day: Día del mes en que se realizó el último contacto.
month: Mes del último contacto.
duration: Duración de la última llamada (en segundos).
campaign: Número de contactos realizados durante la campaña actual.
pdays: Número de días transcurridos desde el último contacto previo (valor -1 indica que no hubo contacto anterior).
previous: Número de contactos previos al actual.
poutcome: Resultado de una campaña anterior (éxito, fracaso, desconocido).
y: Variable objetivo que indica si el cliente aceptó (yes) o no aceptó (no) contratar un depósito a plazo fijo.
La finalidad detras de este estudio es predecir si un cliente aceptara o no la oferta del contrato de un deposito a plazo fijo a partir de la informacion recolectada. Esto le permitira al banco poder mejorar y enrutar las campañas de marketing hacia aquellas opciones que les permitan alcanzar una mayor aceptacion de su oferta de deposito.</p>
<p><strong>Comienzo del EDA</strong></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb2-1" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;bank.csv&quot;</span>,<span class="at">sep=</span><span class="st">&quot;;&quot;</span>)</span>
<span id="cb2-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb2-2" tabindex="-1"></a><span class="fu">head</span>(datos, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   age         job marital education default balance housing loan  contact day
## 1  30  unemployed married   primary      no    1787      no   no cellular  19
## 2  33    services married secondary      no    4789     yes  yes cellular  11
## 3  35  management  single  tertiary      no    1350     yes   no cellular  16
## 4  30  management married  tertiary      no    1476     yes  yes  unknown   3
## 5  59 blue-collar married secondary      no       0     yes   no  unknown   5
##   month duration campaign pdays previous poutcome  y
## 1   oct       79        1    -1        0  unknown no
## 2   may      220        1   339        4  failure no
## 3   apr      185        1   330        1  failure no
## 4   jun      199        4    -1        0  unknown no
## 5   may      226        1    -1        0  unknown no</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb4-1" tabindex="-1"></a><span class="fu">dim</span>(datos)</span></code></pre></div>
<pre><code>## [1] 4521   17</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb6-1" tabindex="-1"></a><span class="fu">colnames</span>(datos)</span></code></pre></div>
<pre><code>##  [1] &quot;age&quot;       &quot;job&quot;       &quot;marital&quot;   &quot;education&quot; &quot;default&quot;   &quot;balance&quot;  
##  [7] &quot;housing&quot;   &quot;loan&quot;      &quot;contact&quot;   &quot;day&quot;       &quot;month&quot;     &quot;duration&quot; 
## [13] &quot;campaign&quot;  &quot;pdays&quot;     &quot;previous&quot;  &quot;poutcome&quot;  &quot;y&quot;</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb8-1" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    4521 obs. of  17 variables:
##  $ age      : int  30 33 35 30 59 35 36 39 41 43 ...
##  $ job      : chr  &quot;unemployed&quot; &quot;services&quot; &quot;management&quot; &quot;management&quot; ...
##  $ marital  : chr  &quot;married&quot; &quot;married&quot; &quot;single&quot; &quot;married&quot; ...
##  $ education: chr  &quot;primary&quot; &quot;secondary&quot; &quot;tertiary&quot; &quot;tertiary&quot; ...
##  $ default  : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ balance  : int  1787 4789 1350 1476 0 747 307 147 221 -88 ...
##  $ housing  : chr  &quot;no&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ loan     : chr  &quot;no&quot; &quot;yes&quot; &quot;no&quot; &quot;yes&quot; ...
##  $ contact  : chr  &quot;cellular&quot; &quot;cellular&quot; &quot;cellular&quot; &quot;unknown&quot; ...
##  $ day      : int  19 11 16 3 5 23 14 6 14 17 ...
##  $ month    : chr  &quot;oct&quot; &quot;may&quot; &quot;apr&quot; &quot;jun&quot; ...
##  $ duration : int  79 220 185 199 226 141 341 151 57 313 ...
##  $ campaign : int  1 1 1 4 1 2 1 2 2 1 ...
##  $ pdays    : int  -1 339 330 -1 -1 176 330 -1 -1 147 ...
##  $ previous : int  0 4 1 0 0 3 2 0 0 2 ...
##  $ poutcome : chr  &quot;unknown&quot; &quot;failure&quot; &quot;failure&quot; &quot;unknown&quot; ...
##  $ y        : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb10-1" tabindex="-1"></a> datos <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb10-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>day, <span class="sc">-</span>month, <span class="sc">-</span>previous) <span class="ot">-&gt;</span> df</span>
<span id="cb10-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb10-3" tabindex="-1"></a>  <span class="fu">head</span>(df, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   age         job marital education default balance housing loan  contact
## 1  30  unemployed married   primary      no    1787      no   no cellular
## 2  33    services married secondary      no    4789     yes  yes cellular
## 3  35  management  single  tertiary      no    1350     yes   no cellular
## 4  30  management married  tertiary      no    1476     yes  yes  unknown
## 5  59 blue-collar married secondary      no       0     yes   no  unknown
##   duration campaign pdays poutcome  y
## 1       79        1    -1  unknown no
## 2      220        1   339  failure no
## 3      185        1   330  failure no
## 4      199        4    -1  unknown no
## 5      226        1    -1  unknown no</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb12-1" tabindex="-1"></a>  df <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb12-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(),<span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_age NA_job NA_marital NA_education NA_default NA_balance NA_housing
## 1      0      0          0            0          0          0          0
##   NA_loan NA_contact NA_duration NA_campaign NA_pdays NA_poutcome NA_y
## 1       0          0           0           0        0           0    0</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-1" tabindex="-1"></a>  tabla_y <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-2" tabindex="-1"></a>  <span class="fu">count</span>(y, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-3" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia<span class="sc">/</span><span class="fu">sum</span>(Frecuencia)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>),</span>
<span id="cb14-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-4" tabindex="-1"></a>    <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb14-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-5" tabindex="-1"></a>  tabla_y <span class="sc">%&gt;%</span> </span>
<span id="cb14-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-6" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(y), <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb14-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-7" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-8" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb14-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-9" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span> <span class="st">&quot;Distribucion interes de deposito a plazo fijo (no/yes)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb14-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-10" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb14-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Interes por el deposito a plazo fijo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Numero de clientes (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-12" tabindex="-1"></a>  <span class="co">#coord_flip() +</span></span>
<span id="cb14-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-13" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb14-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-14" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb14-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-15" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb14-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-16" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb14-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-17" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb14-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-18" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb14-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-19" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>)  </span>
<span id="cb14-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb14-20" tabindex="-1"></a>  ) </span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-1-1.png" width="672" /></p>
<p><strong>Analisis de la tabla y el grafico de barras de la variable “y” (objetivo):</strong></p>
<p>En ambas representaciones visuales, se evidencia que existe una gran mayoria de los clientes, los cuales no estan interesados en hacer parte de la oferta de deposito a plazo fijo con un total de 4000 usuarios (88.55% de la muestra), asi mismo pues, la gran minoria de los encuestados dijo que si a dicha oferta siendo estos el 11.5% de las personas (521 en total). Estos marcadores indican el desbalance que se presenta en la variable objetivo, y que es de sumo cuidado tener en cuenta este desequilibrio para llevar a cabo los modelos predictivos.</p>
<p><strong>Tabla de las variables numericas independientes</strong></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(age),</span>
<span id="cb15-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(age),</span>
<span id="cb15-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-5" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(age),</span>
<span id="cb15-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-6" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(age),</span>
<span id="cb15-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-7" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(age),</span>
<span id="cb15-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-8" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(age),</span>
<span id="cb15-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-9" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(age, <span class="fl">0.25</span>),</span>
<span id="cb15-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-10" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(age, <span class="fl">0.75</span>),</span>
<span id="cb15-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-11" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(age)) <span class="sc">%&gt;%</span></span>
<span id="cb15-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-12" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;age&quot;</span>) <span class="ot">-&gt;</span> variable_age</span>
<span id="cb15-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-13" tabindex="-1"></a></span>
<span id="cb15-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-14" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb15-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-15" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-16" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(balance),</span>
<span id="cb15-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-17" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(balance),</span>
<span id="cb15-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-18" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(balance),</span>
<span id="cb15-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-19" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(balance),</span>
<span id="cb15-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-20" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(balance),</span>
<span id="cb15-21"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-21" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(balance),</span>
<span id="cb15-22"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-22" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(balance, <span class="fl">0.25</span>),</span>
<span id="cb15-23"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-23" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(balance, <span class="fl">0.75</span>),</span>
<span id="cb15-24"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-24" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(balance)) <span class="sc">%&gt;%</span> </span>
<span id="cb15-25"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-25" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;balance&quot;</span>) <span class="ot">-&gt;</span> variable_balance</span>
<span id="cb15-26"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-26" tabindex="-1"></a></span>
<span id="cb15-27"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-27" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb15-28"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-28" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-29"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-29" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(duration),</span>
<span id="cb15-30"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-30" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(duration),</span>
<span id="cb15-31"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-31" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(duration),</span>
<span id="cb15-32"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-32" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(duration),</span>
<span id="cb15-33"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-33" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(duration),</span>
<span id="cb15-34"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-34" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(duration),</span>
<span id="cb15-35"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-35" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(duration, <span class="fl">0.25</span>),</span>
<span id="cb15-36"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-36" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(duration, <span class="fl">0.75</span>),</span>
<span id="cb15-37"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-37" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(duration)) <span class="sc">%&gt;%</span> </span>
<span id="cb15-38"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-38" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;duration&quot;</span>)<span class="ot">-&gt;</span> variable_duration</span>
<span id="cb15-39"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-39" tabindex="-1"></a></span>
<span id="cb15-40"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-40" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb15-41"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-41" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-42"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-42" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(campaign),</span>
<span id="cb15-43"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-43" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(campaign),</span>
<span id="cb15-44"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-44" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(campaign),</span>
<span id="cb15-45"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-45" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(campaign),</span>
<span id="cb15-46"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-46" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(campaign),</span>
<span id="cb15-47"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-47" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(campaign),</span>
<span id="cb15-48"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-48" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(campaign, <span class="fl">0.25</span>),</span>
<span id="cb15-49"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-49" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(campaign, <span class="fl">0.75</span>),</span>
<span id="cb15-50"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-50" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(campaign)) <span class="sc">%&gt;%</span> </span>
<span id="cb15-51"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-51" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;campaign&quot;</span>)<span class="ot">-&gt;</span> variable_campaign</span>
<span id="cb15-52"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-52" tabindex="-1"></a></span>
<span id="cb15-53"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-53" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb15-54"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-54" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb15-55"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-55" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(pdays),</span>
<span id="cb15-56"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-56" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(pdays),</span>
<span id="cb15-57"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-57" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(pdays),</span>
<span id="cb15-58"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-58" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(pdays),</span>
<span id="cb15-59"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-59" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(pdays),</span>
<span id="cb15-60"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-60" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(pdays),</span>
<span id="cb15-61"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-61" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(pdays, <span class="fl">0.25</span>),</span>
<span id="cb15-62"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-62" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(pdays, <span class="fl">0.75</span>),</span>
<span id="cb15-63"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-63" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(pdays)) <span class="sc">%&gt;%</span> </span>
<span id="cb15-64"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-64" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;pdays&quot;</span>)<span class="ot">-&gt;</span> variable_pdays</span>
<span id="cb15-65"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-65" tabindex="-1"></a></span>
<span id="cb15-66"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-66" tabindex="-1"></a><span class="fu">bind_rows</span>(variable_age, variable_balance, variable_duration,variable_campaign,variable_pdays) <span class="sc">%&gt;%</span></span>
<span id="cb15-67"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb15-67" tabindex="-1"></a>  <span class="fu">select</span>(variable, <span class="fu">everything</span>())</span></code></pre></div>
<pre><code>##   variable    n      media  desviacion mediana minimo maximo  Q1   Q3  IQR
## 1      age 4521   41.17010   10.576211      39     19     87  33   49   16
## 2  balance 4521 1422.65782 3009.638142     444  -3313  71188  69 1480 1411
## 3 duration 4521  263.96129  259.856633     185      4   3025 104  329  225
## 4 campaign 4521    2.79363    3.109807       2      1     50   1    3    2
## 5    pdays 4521   39.76664  100.121124      -1     -1    871  -1   -1    0</code></pre>
<p>En la tabla anterior por medio de un analisis estadistico, se evidencia un promedio de edad en los clientes del banco portugues de 41 años, con un rango que arranca desde los 19 años hasta los 87 como el dato maximo registrado, lo que muestra una poblacion adulta diversificada. El saldo promedio anual en las cuentas bancarias muestra una media de 1422 USD y una alta desviacion (Desviacion = 3009); además de unos valores extremos que abarcan saldos en numeros negativos como saldos bastante elevados (Maximo = 71188). Por otro lado, la duracion de las llamadas evidencia una media muestral de 264 segundos aproximadamente, y una desviacion considerable de 259 segundos; la mediana, es decir, el 50% de los datos es menor o igual a 185 segundos, y la duracion de estas llamadas esta comprendida en un intervalo que va desde los 4 segundos hasta los 3025, lo que simboliza una alta dispersion en los datos, y que por tanto puede derivar en sesgos.En relación con el número de contactos durante la campaña (campaign), se registra un promedio de 2,79 contactos (Desviacion = 3,11), con el 50 % de los casos por debajo de 2. Aunque se presentan valores extremos de hasta 50 contactos, la mayoría de los clientes fue contactada pocas veces, tal como refleja el rango intercuartílico comprendido entre los percentiles P25 y P75 (lo mismo que decir Q1 y Q3). A su vez, la variable pdays, que representa los días transcurridos desde el último contacto en campañas anteriores, muestra una media de 39,77 días (Desviacion = 100,12 días). Sin embargo, tanto la mediana como los percentiles P25 y P75 se encuentran en −1, lo que indica que la mayoría de los clientes no había sido contactada previamente. Aun así, existen registros que superan los 800 días, lo que evidencia comportamientos heterogéneos y la posible existencia de distintos segmentos dentro de la base de clientes.</p>
<p><strong>Graficos boxplot (caja y bigotes) de las variables numericas</strong></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb17-1" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb17-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb17-2" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;gridExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     combine</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-1" tabindex="-1"></a><span class="co"># Boxplot de age</span></span>
<span id="cb20-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> age)) <span class="sc">+</span></span>
<span id="cb20-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#1f77b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb20-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de la edad&quot;</span>,</span>
<span id="cb20-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Años&quot;</span>,</span>
<span id="cb20-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb20-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb20-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-3-1.png" width="672" /></p>
<p>El boxplot muestra que la mayoría de las edades se concentran entre 32 y 48 años, donde se ubica el 50% de los individuos.
La edad promedio es de 39 años (± 10 años), lo que refleja una ligera dispersión hacia edades más altas.
El rango total de edades va aproximadamente de 22 a 72 años, y se observan algunos casos atípicos entre los 72 y 90 años, lo que sugiere la presencia de personas considerablemente mayores en comparación con la mayoría.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-1" tabindex="-1"></a><span class="co"># Boxplot de balance</span></span>
<span id="cb21-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> balance)) <span class="sc">+</span></span>
<span id="cb21-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#2f43b1&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del balance de la cuenta&quot;</span>,</span>
<span id="cb21-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Usd&quot;</span>,</span>
<span id="cb21-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb21-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb21-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-4-1.png" width="672" /></p>
<p>La distribución del balance de la cuenta muestra una fuerte asimetría positiva, con la mayoría de los saldos concentrados cerca de valores bajos y un gran número de valores atípicos que alcanzan hasta 71,188 USD. El balance promedio es de 1,422.66 USD (Desviacion = 3,009.64), mientras que la mediana es de solo 444 USD, lo que refleja que pocos clientes con saldos muy altos elevan el promedio. Además, se observan saldos negativos mínimos de -3,313 USD, lo que indica sobregiros o deudas, y un rango intercuartílico que va de 69 a 1,480 USD, confirmando que la mayoría de los clientes mantiene balances reducidos.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-1" tabindex="-1"></a><span class="co">#Diagrama de boxplot para duration</span></span>
<span id="cb22-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> duration)) <span class="sc">+</span></span>
<span id="cb22-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#2ca02c&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb22-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de la duración de llamada (duration)&quot;</span>,</span>
<span id="cb22-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Segundos&quot;</span>,</span>
<span id="cb22-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb22-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb22-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-5-1.png" width="672" /></p>
<p>La duración de las llamadas presenta una media de aproximadamente 264 segundos (Desviacion = 260), con una mediana de 185 segundos, lo que indica que la mayoría de las llamadas fueron relativamente cortas. El rango intercuartílico va de 104 a 329 segundos, reflejando que el 50 % central de las llamadas dura entre poco menos de 2 y alrededor de 5,5 minutos. Sin embargo, el boxplot revela una marcada asimetría positiva debido a la presencia de múltiples valores atípicos que alcanzan hasta 3025 segundos (más de 50 minutos), lo que sugiere que, aunque la mayoría de las interacciones fueron breves, existen casos puntuales de llamadas excepcionalmente largas.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-1" tabindex="-1"></a><span class="co">#Diagrama de boxplot para campaign</span></span>
<span id="cb23-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> campaign)) <span class="sc">+</span></span>
<span id="cb23-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#ff7f0e&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb23-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del número de contactos (campaign)&quot;</span>,</span>
<span id="cb23-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Número de contactos&quot;</span>,</span>
<span id="cb23-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb23-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb23-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-6-1.png" width="672" /></p>
<p>La variable (campaign) muestra una distribución sesgada positivamente, con la mayoría de los clientes contactados pocas veces (mediana de 2 y Q3 en 3), pero con algunos casos extremos que llegan hasta 50 contactos, lo que eleva la media (2.79) por encima de la mediana. El diagrama de caja confirma la presencia de numerosos valores atípicos por encima del rango intercuartílico, reflejando que la mayor parte de los datos se concentra en valores bajos mientras unos pocos casos muy altos alargan la cola derecha.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-1" tabindex="-1"></a><span class="co"># Diagrama de boxplot para pdays</span></span>
<span id="cb24-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> pdays)) <span class="sc">+</span></span>
<span id="cb24-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9467bd&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Días desde último contacto en campaña anterior (pdays)&quot;</span>,</span>
<span id="cb24-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Días&quot;</span>,</span>
<span id="cb24-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb24-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb24-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-7-1.png" width="672" /></p>
<p>El boxplot de (pdays) muestra una distribución fuertemente sesgada positivamente, donde la mayoría de los clientes tienen valores cercanos a cero días desde el último contacto, concentrándose en el primer cuartil, mientras que existen numerosos valores atípicos muy alejados (hasta más de 800 días) que generan una cola derecha larga. Esto indica que, aunque la mediana es baja, un pequeño grupo de clientes fue contactado después de intervalos de tiempo extremadamente largos, lo que eleva la media y refleja una gran dispersión en la variable.</p>
<p><strong>Ahora procedemos a analizar las variables categoricas:</strong></p>
<p>Tabla agrupada de variables categoricas</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-1" tabindex="-1"></a><span class="co">#Para job</span></span>
<span id="cb25-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-2" tabindex="-1"></a>tabla_job <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-3" tabindex="-1"></a>  <span class="fu">count</span>(job, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb25-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-5" tabindex="-1"></a>         <span class="at">Variable =</span> <span class="st">&quot;job&quot;</span>,</span>
<span id="cb25-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-6" tabindex="-1"></a>         <span class="at">Categoria =</span> job) <span class="sc">%&gt;%</span></span>
<span id="cb25-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-7" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb25-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-8" tabindex="-1"></a><span class="co">#Para marital</span></span>
<span id="cb25-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-9" tabindex="-1"></a>tabla_marital <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb25-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-10" tabindex="-1"></a>  <span class="fu">count</span>(marital, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-11" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb25-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-12" tabindex="-1"></a>         <span class="at">Variable =</span> <span class="st">&quot;marital&quot;</span>,</span>
<span id="cb25-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-13" tabindex="-1"></a>         <span class="at">Categoria =</span> marital) <span class="sc">%&gt;%</span></span>
<span id="cb25-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-14" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb25-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-15" tabindex="-1"></a></span>
<span id="cb25-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-16" tabindex="-1"></a><span class="co">#Para education</span></span>
<span id="cb25-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-17" tabindex="-1"></a>tabla_education <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb25-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-18" tabindex="-1"></a>  <span class="fu">count</span>(education, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-19" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb25-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-20" tabindex="-1"></a>         <span class="at">Variable =</span> <span class="st">&quot;education&quot;</span>,</span>
<span id="cb25-21"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-21" tabindex="-1"></a>         <span class="at">Categoria =</span> education) <span class="sc">%&gt;%</span></span>
<span id="cb25-22"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-22" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb25-23"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-23" tabindex="-1"></a></span>
<span id="cb25-24"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-24" tabindex="-1"></a><span class="co">#Para default</span></span>
<span id="cb25-25"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-25" tabindex="-1"></a>tabla_default <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb25-26"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-26" tabindex="-1"></a>  <span class="fu">count</span>(default, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-27"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-27" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb25-28"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-28" tabindex="-1"></a>         <span class="at">Variable =</span> <span class="st">&quot;default&quot;</span>,</span>
<span id="cb25-29"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-29" tabindex="-1"></a>         <span class="at">Categoria =</span> default) <span class="sc">%&gt;%</span></span>
<span id="cb25-30"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-30" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb25-31"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-31" tabindex="-1"></a></span>
<span id="cb25-32"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-32" tabindex="-1"></a><span class="co">#Para housing</span></span>
<span id="cb25-33"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-33" tabindex="-1"></a>tabla_housing <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb25-34"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-34" tabindex="-1"></a>  <span class="fu">count</span>(housing, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-35"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-35" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb25-36"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-36" tabindex="-1"></a>         <span class="at">Variable =</span> <span class="st">&quot;housing&quot;</span>,</span>
<span id="cb25-37"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-37" tabindex="-1"></a>         <span class="at">Categoria =</span> housing) <span class="sc">%&gt;%</span></span>
<span id="cb25-38"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-38" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb25-39"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-39" tabindex="-1"></a></span>
<span id="cb25-40"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-40" tabindex="-1"></a><span class="co">#Para loan</span></span>
<span id="cb25-41"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-41" tabindex="-1"></a>tabla_loan <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb25-42"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-42" tabindex="-1"></a>  <span class="fu">count</span>(loan, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-43"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-43" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb25-44"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-44" tabindex="-1"></a>         <span class="at">Variable =</span> <span class="st">&quot;loan&quot;</span>,</span>
<span id="cb25-45"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-45" tabindex="-1"></a>         <span class="at">Categoria =</span> loan) <span class="sc">%&gt;%</span></span>
<span id="cb25-46"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-46" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb25-47"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-47" tabindex="-1"></a></span>
<span id="cb25-48"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-48" tabindex="-1"></a><span class="co">#Para contact</span></span>
<span id="cb25-49"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-49" tabindex="-1"></a>tabla_contact <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb25-50"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-50" tabindex="-1"></a>  <span class="fu">count</span>(contact, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-51"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-51" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb25-52"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-52" tabindex="-1"></a>         <span class="at">Variable =</span> <span class="st">&quot;contact&quot;</span>,</span>
<span id="cb25-53"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-53" tabindex="-1"></a>         <span class="at">Categoria =</span> contact) <span class="sc">%&gt;%</span></span>
<span id="cb25-54"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-54" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb25-55"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-55" tabindex="-1"></a></span>
<span id="cb25-56"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-56" tabindex="-1"></a><span class="co">#Para poutcome</span></span>
<span id="cb25-57"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-57" tabindex="-1"></a>tabla_poutcome <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb25-58"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-58" tabindex="-1"></a>  <span class="fu">count</span>(poutcome, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-59"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-59" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb25-60"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-60" tabindex="-1"></a>         <span class="at">Variable =</span> <span class="st">&quot;poutcome&quot;</span>,</span>
<span id="cb25-61"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-61" tabindex="-1"></a>         <span class="at">Categoria =</span> poutcome) <span class="sc">%&gt;%</span></span>
<span id="cb25-62"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-62" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb25-63"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-63" tabindex="-1"></a></span>
<span id="cb25-64"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-64" tabindex="-1"></a><span class="co">#Todas las tablas</span></span>
<span id="cb25-65"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-65" tabindex="-1"></a><span class="fu">bind_rows</span>(tabla_job, tabla_marital, tabla_education,tabla_default,</span>
<span id="cb25-66"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb25-66" tabindex="-1"></a>          tabla_housing, tabla_loan,tabla_contact, tabla_poutcome)</span></code></pre></div>
<pre><code>##     Variable     Categoria Frecuencia Porcentaje
## 1        job        admin.        478      10.57
## 2        job   blue-collar        946      20.92
## 3        job  entrepreneur        168       3.72
## 4        job     housemaid        112       2.48
## 5        job    management        969      21.43
## 6        job       retired        230       5.09
## 7        job self-employed        183       4.05
## 8        job      services        417       9.22
## 9        job       student         84       1.86
## 10       job    technician        768      16.99
## 11       job    unemployed        128       2.83
## 12       job       unknown         38       0.84
## 13   marital      divorced        528      11.68
## 14   marital       married       2797      61.87
## 15   marital        single       1196      26.45
## 16 education       primary        678      15.00
## 17 education     secondary       2306      51.01
## 18 education      tertiary       1350      29.86
## 19 education       unknown        187       4.14
## 20   default            no       4445      98.32
## 21   default           yes         76       1.68
## 22   housing            no       1962      43.40
## 23   housing           yes       2559      56.60
## 24      loan            no       3830      84.72
## 25      loan           yes        691      15.28
## 26   contact      cellular       2896      64.06
## 27   contact     telephone        301       6.66
## 28   contact       unknown       1324      29.29
## 29  poutcome       failure        490      10.84
## 30  poutcome         other        197       4.36
## 31  poutcome       success        129       2.85
## 32  poutcome       unknown       3705      81.95</code></pre>
<p>Viendo la variable (marital), la mayoria de los clientes registrados (61,87%) son de estado civil casados, seguidos de 1196 que se declaran solteros (26,45%) y el resto son divorciados (11,68%). En cuanto a la educacion, la mayoria de estos usuarios ha cursado hasta niveles de secundaria con 2306 personas(51,01%), seguidos de personas que han tenido niveles de educacion terciaria como universidades, institutos tecnicos, maestrias, postgrados, etc; con un porcentaje de 29,86% lo que es equivalente a 1350 individuos, luego se ubican las personas con una educacion primaria como maximo, siendo 678 personas, las cuales representan un 15% de la muestra y por ultimo estan aquellos que no registran algun tipo de nivel de educacion. La variable (default) muestra si los clientes presentan credito en incumplimiento, a lo que la gran mayoria dice que no, 4445 personas (98,32%) niegan tener un credito sin cumplir, y solo 76 personas afirman estar incumpliendo con dicho credito, por otra parte, el 56,6% de los usuarios dijo que si despues de preguntarles si tenian un credito hipotecario, el otro 43,4% expuso que no tenian credito hipotecario; tambien se dio a conocer que la mayoria no tiene creditos personales, fueron 3830 personas las que negaron tener este tipo de credito, representando un 84,72% de la muestra; el otro 15,28% (691 usuarios) dijeron que si. Ademas, se recogio informacion acerca del metodo utilizado para contactarlos, donde mayoritariamente (64,06%) dijeron que se habian comunicado con ellos via celular, luego con casi el 30% estan las personas que desconocen el tipo de comunicacion que usaron, y con el porcentaje mas bajo (6,66%) se pueden observar las personas que tuvieron contacto con el banco por medio de un telefono fijo. En los resultados de campañas anteriores (poutcome), 3705 usuarios manifestaron desconocer el resultado de campañas anteriores, siendo estos la gran mayoria con un 81,95%, seguidos del 10,84% que señalan a las campañas previas como un absoluto fracaso, luego se ubican con un 4,36% (197 personas) aquellos que tienen otra percepcion frente a estas campañas, y por ultimo, vemos a la gran minoria que establece que las campañas fueron un rotundo exito (129 personas que representan el 2,85%). En cuanto a las ocupaciones de los usuarios, se observa que las más comunes son “management” (21.43%), “blue-collar” (20.92%) y “technician” (16.99%), lo que indica que estos tres grupos representan casi el 60% de la muestra total. En contraste, las personas con ocupaciones que se desconocen (0.84%), estudiantes (1.86%) y empleados domesticos (2.48%) tienen una representación mucho menor. Esto sugiere una muestra compuesta principalmente por trabajadores con cargos administrativos, técnicos y operativos, lo cual podría reflejar el perfil laboral de una muestra económicamente activa en sectores formales. Entre otros trabajos consignados en la informacion, podemos observar 168 emprendedores (3,72%), 478 administradores (10,57%), 230 personas retiradas (5,09%), 183 trabajadores autonomos (4,05%), 417 que se ocupan de servicios que involucran atencion directa al publico (9,22%) y 128 desempleados (2,83%).</p>
<p><strong>Graficos de barras para cada variable categorica</strong></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-1" tabindex="-1"></a>grafico_default <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-2" tabindex="-1"></a>  <span class="fu">count</span>(default, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb27-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb27-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-5" tabindex="-1"></a></span>
<span id="cb27-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-6" tabindex="-1"></a>grafico_default <span class="sc">%&gt;%</span> </span>
<span id="cb27-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> default, <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb27-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb27-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable default&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb27-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;¿Tiene crédito en incumplimiento?&quot;</span>, </span>
<span id="cb27-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb27-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb27-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb27-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-17" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb27-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-18" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb27-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-19" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>()</span>
<span id="cb27-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb27-20" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-9-1.png" width="672" /></p>
<p>La grafica de la variable (default) nos muestra como el 98,3% de los clientes del banco encuestados en la muestra no estan incumpliendo con el pago de un credito, en comparacion con el 1,7% de aquellas que si estan incumpliendo. Esta gran diferencia permite conocer una muestra de personas que se encuentran al dia con sus compromisos financieros, y que aquellas personas que tienen faltas son muy pocas.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-1" tabindex="-1"></a>grafico_job <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-2" tabindex="-1"></a>  <span class="fu">count</span>(job, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb28-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-4" tabindex="-1"></a>    <span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb28-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-5" tabindex="-1"></a>    <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>)</span>
<span id="cb28-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-6" tabindex="-1"></a>  )</span>
<span id="cb28-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-7" tabindex="-1"></a></span>
<span id="cb28-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-8" tabindex="-1"></a>grafico_job <span class="sc">%&gt;%</span></span>
<span id="cb28-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-9" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(job, <span class="sc">-</span>Frecuencia), <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb28-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-10" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb28-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-11" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb28-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-12" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> Etiqueta),</span>
<span id="cb28-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-13" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.8</span>,           </span>
<span id="cb28-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-14" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">3.5</span>,             </span>
<span id="cb28-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-15" tabindex="-1"></a>    <span class="at">fontface =</span> <span class="st">&quot;bold&quot;</span></span>
<span id="cb28-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-16" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-17" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable job&quot;</span>) <span class="sc">+</span></span>
<span id="cb28-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-18" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.20</span>))) <span class="sc">+</span> </span>
<span id="cb28-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-19" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-20" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Ocupación&quot;</span>,</span>
<span id="cb28-21"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-21" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span></span>
<span id="cb28-22"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-22" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-23"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-23" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb28-24"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-24" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb28-25"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-25" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb28-26"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-26" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb28-27"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-27" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb28-28"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-28" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb28-29"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-29" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(</span>
<span id="cb28-30"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-30" tabindex="-1"></a>      <span class="at">angle =</span> <span class="dv">45</span>,</span>
<span id="cb28-31"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-31" tabindex="-1"></a>      <span class="at">hjust =</span> <span class="dv">1</span>,</span>
<span id="cb28-32"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-32" tabindex="-1"></a>      <span class="at">size =</span> <span class="dv">10</span></span>
<span id="cb28-33"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-33" tabindex="-1"></a>    ),</span>
<span id="cb28-34"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-34" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb28-35"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-35" tabindex="-1"></a>    <span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">30</span>, <span class="dv">10</span>)</span>
<span id="cb28-36"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb28-36" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-10-1.png" width="672" /></p>
<p>Respecto a las ocupaciones de los participantes, se destaca que los grupos más representativos son quienes se desempeñan en áreas de gestión (21.43%), trabajos operativos o manuales (20.92%) y funciones técnicas (16.99%), concentrando cerca del 60% del total. En cambio, los estudiantes (1.86%), empleados domésticos (2.48%) y aquellos cuya ocupación no fue especificada (0.84%) tienen una presencia marginal. Esto revela que la muestra está compuesta mayoritariamente por personas activas en el mercado laboral formal, con roles administrativos, técnicos y operativos. Además, se incluyen otros perfiles como 168 emprendedores (3.72%), 478 administradores (10.57%), 230 jubilados (5.09%), 183 trabajadores independientes (4.05%), 417 empleados en atención al público (9.22%) y 128 personas desempleadas (2.83%), lo que aporta mayor diversidad al panorama ocupacional.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-1" tabindex="-1"></a>grafico_marital <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-2" tabindex="-1"></a>  <span class="fu">count</span>(marital, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb29-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb29-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-5" tabindex="-1"></a></span>
<span id="cb29-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-6" tabindex="-1"></a>grafico_marital <span class="sc">%&gt;%</span> </span>
<span id="cb29-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> marital, <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb29-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb29-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb29-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable marital&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb29-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Estado Civil&quot;</span>, </span>
<span id="cb29-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb29-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb29-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb29-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-17" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb29-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-18" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb29-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-19" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>()</span>
<span id="cb29-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb29-20" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-11-1.png" width="672" /></p>
<p>La variable (marital) muestra que la mayoría de los clientes registrados son casados (61.87%), seguidos por 1,196 solteros (26.45%), mientras que el 11.68% restante corresponde a personas divorciadas; lo que sugiere una base de datos principalmente formada por personas con nexos conyugales.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-1" tabindex="-1"></a>grafico_education <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-2" tabindex="-1"></a>  <span class="fu">count</span>(education, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb30-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb30-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-5" tabindex="-1"></a></span>
<span id="cb30-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-6" tabindex="-1"></a>grafico_education <span class="sc">%&gt;%</span> </span>
<span id="cb30-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> education, <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb30-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb30-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb30-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable education&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb30-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Nivel de Educacion (estudio)&quot;</span>, </span>
<span id="cb30-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb30-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb30-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb30-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-17" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb30-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-18" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb30-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-19" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>()</span>
<span id="cb30-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb30-20" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-12-1.png" width="672" /></p>
<p>El gráfico muestra que la mayoría de las personas encuestadas tienen educación secundaria, representando el 51% (2306 individuos) del total. Le sigue la educación terciaria con un 29.9% (1350 personas), mientras que un 15% (678 personas) alcanzó solo la primaria. Un grupo reducido, el 4.1% (187 personas), no tiene registrado su nivel educativo. Esto indica que el nivel secundario es el más común, mientras que la educación primaria y la falta de información son minoritarias.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-1" tabindex="-1"></a>grafico_housing <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-2" tabindex="-1"></a>  <span class="fu">count</span>(housing, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb31-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb31-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-5" tabindex="-1"></a></span>
<span id="cb31-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-6" tabindex="-1"></a>grafico_housing <span class="sc">%&gt;%</span> </span>
<span id="cb31-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> housing, <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb31-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb31-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb31-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable housing&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb31-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;¿Tiene credito hipotecario?&quot;</span>, </span>
<span id="cb31-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb31-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb31-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb31-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-17" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb31-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-18" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb31-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-19" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>()</span>
<span id="cb31-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb31-20" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-13-1.png" width="672" /></p>
<p>El gráfico indica que la mayoría de las personas encuestadas, un 56.6% (2559 individuos), posee un crédito hipotecario, mientras que el 43.4% restante (1962 personas) no lo tiene. Esto refleja que más de la mitad de la población analizada mantiene compromisos financieros asociados a la adquisición de vivienda.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-1" tabindex="-1"></a>grafico_loan <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-2" tabindex="-1"></a>  <span class="fu">count</span>(loan, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb32-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb32-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-5" tabindex="-1"></a></span>
<span id="cb32-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-6" tabindex="-1"></a>grafico_loan <span class="sc">%&gt;%</span> </span>
<span id="cb32-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> loan, <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb32-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb32-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb32-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable loan&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb32-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;¿Tiene credito personal?&quot;</span>, </span>
<span id="cb32-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb32-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb32-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb32-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-17" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb32-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-18" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb32-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-19" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>()</span>
<span id="cb32-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb32-20" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-14-1.png" width="672" /></p>
<p>El gráfico muestra que la gran mayoría de los encuestados, un 84.7% (3830 personas), no tiene un crédito personal, mientras que solo el 15.3% (691 personas) sí cuenta con este tipo de préstamo. Esto evidencia que el uso de créditos personales es considerablemente menor en comparación con quienes no los poseen.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-1" tabindex="-1"></a>grafico_contact <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-2" tabindex="-1"></a>  <span class="fu">count</span>(contact, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb33-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb33-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-5" tabindex="-1"></a></span>
<span id="cb33-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-6" tabindex="-1"></a>grafico_contact <span class="sc">%&gt;%</span> </span>
<span id="cb33-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> contact, <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb33-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb33-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb33-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable contact&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb33-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tipo de comunicacion utilizada&quot;</span>, </span>
<span id="cb33-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb33-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb33-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb33-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-17" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb33-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-18" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb33-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-19" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>()</span>
<span id="cb33-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb33-20" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-15-1.png" width="672" /></p>
<p>El gráfico revela que el medio de comunicación más utilizado es el teléfono celular, con un 64.1% (2896 casos), seguido por un 29.3% (1324 casos) donde el tipo de contacto es desconocido. En contraste, solo el 6.7% (301 casos) utiliza el teléfono fijo. Esto indica una clara preferencia por el celular como canal de comunicación, mientras que el uso del teléfono fijo es muy reducido.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-1" tabindex="-1"></a>grafico_poutcome <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-2" tabindex="-1"></a>  <span class="fu">count</span>(poutcome, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb34-4"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb34-5"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-5" tabindex="-1"></a></span>
<span id="cb34-6"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-6" tabindex="-1"></a>grafico_poutcome <span class="sc">%&gt;%</span> </span>
<span id="cb34-7"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> poutcome, <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb34-8"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb34-9"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb34-10"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable poutcome&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-11"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb34-12"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Resultado de una campaña anterior&quot;</span>, </span>
<span id="cb34-13"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-13" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb34-14"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb34-15"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-15" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb34-16"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-16" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb34-17"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-17" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb34-18"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-18" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb34-19"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-19" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>()</span>
<span id="cb34-20"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html#cb34-20" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="figs-marin/unnamed-chunk-16-1.png" width="672" /></p>
<p>El gráfico muestra que en el 82% de los casos (3705 registros) se desconoce el resultado de la campaña anterior, mientras que un 10.8% (490 casos) terminó en fracaso y solo un 2.9% (129 casos) fue exitoso. El 4.4% restante (197 casos) se clasifica como “otro”. Esto evidencia una gran carencia de información sobre campañas previas y una baja tasa de éxito entre los casos conocidos.</p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="análisis-exploratorio-bivariado.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/01-Marin.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["mi-libro.pdf", "mi-libro.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
