<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capitulo 3 Bivariado con variables categoricas | Analisis exploratorio de datos (EDA)</title>
  <meta name="description" content="Este es un libro creado con bookdown." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capitulo 3 Bivariado con variables categoricas | Analisis exploratorio de datos (EDA)" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este es un libro creado con bookdown." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capitulo 3 Bivariado con variables categoricas | Analisis exploratorio de datos (EDA)" />
  
  <meta name="twitter:description" content="Este es un libro creado con bookdown." />
  

<meta name="author" content="Juan Marín, Santiago Hurtado y Andrés Parejo" />


<meta name="date" content="2025-10-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="análisis-exploratorio-bivariado.html"/>
<link rel="next" href="referencias.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Libro bookdown</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path=""><a href="#introducci%C3%B3n"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="1" data-path="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html"><a href="analisis-de-la-variable-objetivo-numericas-y-categoricas-indepentiendes.html"><i class="fa fa-check"></i><b>1</b> Analisis de la variable objetivo, numericas y categoricas indepentiendes</a></li>
<li class="chapter" data-level="2" data-path="03-Parejo.html"><a href="#an%C3%A1lisis-exploratorio-bivariado"><i class="fa fa-check"></i><b>2</b> Análisis exploratorio bivariado</a></li>
<li class="chapter" data-level="3" data-path="bivariado-con-variables-categoricas.html"><a href="bivariado-con-variables-categoricas.html"><i class="fa fa-check"></i><b>3</b> Bivariado con variables categoricas</a>
<ul>
<li class="chapter" data-level="3.1" data-path="bivariado-con-variables-categoricas.html"><a href="bivariado-con-variables-categoricas.html#tecnicas-inferenciales-entre-las-variables-cuantitativas-y-la-variable-objetivo"><i class="fa fa-check"></i><b>3.1</b> Tecnicas inferenciales entre las variables cuantitativas y la variable objetivo</a></li>
<li class="chapter" data-level="3.2" data-path="bivariado-con-variables-categoricas.html"><a href="bivariado-con-variables-categoricas.html#tecnicas-inferenciales-entre-las-variables-categoricas-y-la-variable-objetivo"><i class="fa fa-check"></i><b>3.2</b> Tecnicas inferenciales entre las variables categoricas y la variable objetivo</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>4</b> Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analisis exploratorio de datos (EDA)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="bivariado-con-variables-categoricas" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capitulo 3</span> Bivariado con variables categoricas<a href="bivariado-con-variables-categoricas.html#bivariado-con-variables-categoricas" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<ul>
<li><strong>Tabla de comparación de y con marital.</strong></li>
</ul>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="bivariado-con-variables-categoricas.html#cb1-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="bivariado-con-variables-categoricas.html#cb1-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="bivariado-con-variables-categoricas.html#cb1-3" tabindex="-1"></a>  <span class="fu">count</span>(marital, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="bivariado-con-variables-categoricas.html#cb1-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> marital,</span>
<span id="cb1-5"><a href="bivariado-con-variables-categoricas.html#cb1-5" tabindex="-1"></a>    <span class="at">variable =</span> <span class="st">&quot;marital&quot;</span>,</span>
<span id="cb1-6"><a href="bivariado-con-variables-categoricas.html#cb1-6" tabindex="-1"></a>    <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-7"><a href="bivariado-con-variables-categoricas.html#cb1-7" tabindex="-1"></a>  <span class="fu">select</span>(y, variable, categoria, n, porcentaje)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
## # Groups:   y [2]
##   y     variable categoria     n porcentaje
##   &lt;fct&gt; &lt;chr&gt;    &lt;fct&gt;     &lt;int&gt;      &lt;dbl&gt;
## 1 no    marital  divorced    451       11.3
## 2 no    marital  married    2520       63  
## 3 no    marital  single     1029       25.7
## 4 yes   marital  divorced     77       14.8
## 5 yes   marital  married     277       53.2
## 6 yes   marital  single      167       32.1</code></pre>
<ul>
<li><strong>Tabla de comparación de y con job.</strong></li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="bivariado-con-variables-categoricas.html#cb3-1" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="bivariado-con-variables-categoricas.html#cb3-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y, job) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="bivariado-con-variables-categoricas.html#cb3-3" tabindex="-1"></a>  <span class="fu">count</span>(<span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="bivariado-con-variables-categoricas.html#cb3-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>)</span></code></pre></div>
<pre><code>## # A tibble: 24 × 4
## # Groups:   y, job [24]
##    y     job               n porcentaje
##    &lt;fct&gt; &lt;fct&gt;         &lt;int&gt;      &lt;dbl&gt;
##  1 no    admin.          420        100
##  2 no    blue-collar     877        100
##  3 no    entrepreneur    153        100
##  4 no    housemaid        98        100
##  5 no    management      838        100
##  6 no    retired         176        100
##  7 no    self-employed   163        100
##  8 no    services        379        100
##  9 no    student          65        100
## 10 no    technician      685        100
## # ℹ 14 more rows</code></pre>
<ul>
<li><strong>Tabla de comparación de y con education.</strong></li>
</ul>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="bivariado-con-variables-categoricas.html#cb5-1" tabindex="-1"></a><span class="co"># Education</span></span>
<span id="cb5-2"><a href="bivariado-con-variables-categoricas.html#cb5-2" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="bivariado-con-variables-categoricas.html#cb5-3" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="bivariado-con-variables-categoricas.html#cb5-4" tabindex="-1"></a>  <span class="fu">count</span>(education, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="bivariado-con-variables-categoricas.html#cb5-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> education,</span>
<span id="cb5-6"><a href="bivariado-con-variables-categoricas.html#cb5-6" tabindex="-1"></a>         <span class="at">variable =</span> <span class="st">&quot;education&quot;</span>,</span>
<span id="cb5-7"><a href="bivariado-con-variables-categoricas.html#cb5-7" tabindex="-1"></a>         <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-8"><a href="bivariado-con-variables-categoricas.html#cb5-8" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span></code></pre></div>
<pre><code>## # A tibble: 8 × 4
## # Groups:   y [2]
##   y     categoria     n porcentaje
##   &lt;fct&gt; &lt;fct&gt;     &lt;int&gt;      &lt;dbl&gt;
## 1 no    primary     614      15.4 
## 2 no    secondary  2061      51.5 
## 3 no    tertiary   1157      28.9 
## 4 no    unknown     168       4.2 
## 5 yes   primary      64      12.3 
## 6 yes   secondary   245      47.0 
## 7 yes   tertiary    193      37.0 
## 8 yes   unknown      19       3.65</code></pre>
<ul>
<li><strong>Tabla de comparación de y con housing.</strong></li>
</ul>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="bivariado-con-variables-categoricas.html#cb7-1" tabindex="-1"></a><span class="co"># Housing</span></span>
<span id="cb7-2"><a href="bivariado-con-variables-categoricas.html#cb7-2" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="bivariado-con-variables-categoricas.html#cb7-3" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="bivariado-con-variables-categoricas.html#cb7-4" tabindex="-1"></a>  <span class="fu">count</span>(housing, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="bivariado-con-variables-categoricas.html#cb7-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> housing,</span>
<span id="cb7-6"><a href="bivariado-con-variables-categoricas.html#cb7-6" tabindex="-1"></a>         <span class="at">variable =</span> <span class="st">&quot;housing&quot;</span>,</span>
<span id="cb7-7"><a href="bivariado-con-variables-categoricas.html#cb7-7" tabindex="-1"></a>         <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-8"><a href="bivariado-con-variables-categoricas.html#cb7-8" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 4
## # Groups:   y [2]
##   y     categoria     n porcentaje
##   &lt;fct&gt; &lt;fct&gt;     &lt;int&gt;      &lt;dbl&gt;
## 1 no    no         1661       41.5
## 2 no    yes        2339       58.5
## 3 yes   no          301       57.8
## 4 yes   yes         220       42.2</code></pre>
<ul>
<li><strong>Tabla de comparación de y con loan.</strong></li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="bivariado-con-variables-categoricas.html#cb9-1" tabindex="-1"></a><span class="co"># Loan</span></span>
<span id="cb9-2"><a href="bivariado-con-variables-categoricas.html#cb9-2" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="bivariado-con-variables-categoricas.html#cb9-3" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="bivariado-con-variables-categoricas.html#cb9-4" tabindex="-1"></a>  <span class="fu">count</span>(loan, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="bivariado-con-variables-categoricas.html#cb9-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> loan,</span>
<span id="cb9-6"><a href="bivariado-con-variables-categoricas.html#cb9-6" tabindex="-1"></a>         <span class="at">variable =</span> <span class="st">&quot;loan&quot;</span>,</span>
<span id="cb9-7"><a href="bivariado-con-variables-categoricas.html#cb9-7" tabindex="-1"></a>         <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-8"><a href="bivariado-con-variables-categoricas.html#cb9-8" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 4
## # Groups:   y [2]
##   y     categoria     n porcentaje
##   &lt;fct&gt; &lt;fct&gt;     &lt;int&gt;      &lt;dbl&gt;
## 1 no    no         3352      83.8 
## 2 no    yes         648      16.2 
## 3 yes   no          478      91.7 
## 4 yes   yes          43       8.25</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="bivariado-con-variables-categoricas.html#cb11-1" tabindex="-1"></a>data_plot <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="bivariado-con-variables-categoricas.html#cb11-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="bivariado-con-variables-categoricas.html#cb11-3" tabindex="-1"></a>  <span class="fu">count</span>(default, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="bivariado-con-variables-categoricas.html#cb11-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> default,</span>
<span id="cb11-5"><a href="bivariado-con-variables-categoricas.html#cb11-5" tabindex="-1"></a>    <span class="at">variable =</span> <span class="st">&quot;default&quot;</span>,</span>
<span id="cb11-6"><a href="bivariado-con-variables-categoricas.html#cb11-6" tabindex="-1"></a>    <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="bivariado-con-variables-categoricas.html#cb11-7" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span>
<span id="cb11-8"><a href="bivariado-con-variables-categoricas.html#cb11-8" tabindex="-1"></a></span>
<span id="cb11-9"><a href="bivariado-con-variables-categoricas.html#cb11-9" tabindex="-1"></a><span class="co"># Gráfica de barras agrupadas con etiquetas</span></span>
<span id="cb11-10"><a href="bivariado-con-variables-categoricas.html#cb11-10" tabindex="-1"></a>data_plot <span class="sc">%&gt;%</span> </span>
<span id="cb11-11"><a href="bivariado-con-variables-categoricas.html#cb11-11" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> categoria, <span class="at">y =</span> n, <span class="at">fill =</span> y)) <span class="sc">+</span></span>
<span id="cb11-12"><a href="bivariado-con-variables-categoricas.html#cb11-12" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>)) <span class="sc">+</span></span>
<span id="cb11-13"><a href="bivariado-con-variables-categoricas.html#cb11-13" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, <span class="fu">round</span>(porcentaje, <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)),</span>
<span id="cb11-14"><a href="bivariado-con-variables-categoricas.html#cb11-14" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>),</span>
<span id="cb11-15"><a href="bivariado-con-variables-categoricas.html#cb11-15" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>,</span>
<span id="cb11-16"><a href="bivariado-con-variables-categoricas.html#cb11-16" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb11-17"><a href="bivariado-con-variables-categoricas.html#cb11-17" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Historial de impago (default)&quot;</span>,</span>
<span id="cb11-18"><a href="bivariado-con-variables-categoricas.html#cb11-18" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Historial de impago (default)&quot;</span>,</span>
<span id="cb11-19"><a href="bivariado-con-variables-categoricas.html#cb11-19" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Cantidad de clientes&quot;</span></span>
<span id="cb11-20"><a href="bivariado-con-variables-categoricas.html#cb11-20" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-21"><a href="bivariado-con-variables-categoricas.html#cb11-21" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb11-22"><a href="bivariado-con-variables-categoricas.html#cb11-22" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;no&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;yes&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>))</span></code></pre></div>
<p><img src="figs-parejo/unnamed-chunk-7-1.png" width="768" /></p>
<p><strong>Interpretación Default vs Y:</strong>
La distribución del historial de impago muestra un patrón muy claro y relevante para las estrategias de marketing bancario. Entre los clientes con respuesta afirmativa (<code>yes</code>), prácticamente todos (&gt;99%) no tienen historial de impago, mientras que menos del 1% presenta default. Esta tendencia se mantiene de forma similar en el grupo que respondió negativamente (<code>no</code>), donde también más del 98% no tiene historial de impago. Sin embargo, la diferencia clave radica en que los clientes sin historial de impago muestran una mayor predisposición a aceptar el producto bancario. Esta variable es un fuerte predictor de confiabilidad crediticia y sugiere que el banco debe enfocar sus esfuerzos en clientes con historiales crediticios limpios para maximizar las tasas de conversión.</p>
<p>#job vs y</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="bivariado-con-variables-categoricas.html#cb12-1" tabindex="-1"></a>data_plot <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="bivariado-con-variables-categoricas.html#cb12-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="bivariado-con-variables-categoricas.html#cb12-3" tabindex="-1"></a>  <span class="fu">count</span>(job, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="bivariado-con-variables-categoricas.html#cb12-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-5"><a href="bivariado-con-variables-categoricas.html#cb12-5" tabindex="-1"></a>    <span class="at">categoria =</span> job,</span>
<span id="cb12-6"><a href="bivariado-con-variables-categoricas.html#cb12-6" tabindex="-1"></a>    <span class="at">variable =</span> <span class="st">&quot;job&quot;</span>,</span>
<span id="cb12-7"><a href="bivariado-con-variables-categoricas.html#cb12-7" tabindex="-1"></a>    <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb12-8"><a href="bivariado-con-variables-categoricas.html#cb12-8" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="bivariado-con-variables-categoricas.html#cb12-9" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span>
<span id="cb12-10"><a href="bivariado-con-variables-categoricas.html#cb12-10" tabindex="-1"></a></span>
<span id="cb12-11"><a href="bivariado-con-variables-categoricas.html#cb12-11" tabindex="-1"></a>data_plot <span class="sc">%&gt;%</span></span>
<span id="cb12-12"><a href="bivariado-con-variables-categoricas.html#cb12-12" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> <span class="fu">reorder</span>(categoria, <span class="sc">-</span>n, sum)) <span class="sc">%&gt;%</span></span>
<span id="cb12-13"><a href="bivariado-con-variables-categoricas.html#cb12-13" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> categoria, <span class="at">y =</span> n, <span class="at">fill =</span> y)) <span class="sc">+</span></span>
<span id="cb12-14"><a href="bivariado-con-variables-categoricas.html#cb12-14" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">width =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb12-15"><a href="bivariado-con-variables-categoricas.html#cb12-15" tabindex="-1"></a>  <span class="fu">geom_text</span>(</span>
<span id="cb12-16"><a href="bivariado-con-variables-categoricas.html#cb12-16" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">(&quot;</span>, <span class="fu">round</span>(porcentaje, <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)),</span>
<span id="cb12-17"><a href="bivariado-con-variables-categoricas.html#cb12-17" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>),</span>
<span id="cb12-18"><a href="bivariado-con-variables-categoricas.html#cb12-18" tabindex="-1"></a>    <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>,</span>
<span id="cb12-19"><a href="bivariado-con-variables-categoricas.html#cb12-19" tabindex="-1"></a>    <span class="at">lineheight =</span> <span class="fl">0.9</span>,</span>
<span id="cb12-20"><a href="bivariado-con-variables-categoricas.html#cb12-20" tabindex="-1"></a>    <span class="at">size =</span> <span class="fl">3.5</span></span>
<span id="cb12-21"><a href="bivariado-con-variables-categoricas.html#cb12-21" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-22"><a href="bivariado-con-variables-categoricas.html#cb12-22" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-23"><a href="bivariado-con-variables-categoricas.html#cb12-23" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución por ocupación (job)&quot;</span>,</span>
<span id="cb12-24"><a href="bivariado-con-variables-categoricas.html#cb12-24" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Ocupación&quot;</span>,</span>
<span id="cb12-25"><a href="bivariado-con-variables-categoricas.html#cb12-25" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Cantidad de clientes&quot;</span></span>
<span id="cb12-26"><a href="bivariado-con-variables-categoricas.html#cb12-26" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-27"><a href="bivariado-con-variables-categoricas.html#cb12-27" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.20</span>))) <span class="sc">+</span></span>
<span id="cb12-28"><a href="bivariado-con-variables-categoricas.html#cb12-28" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb12-29"><a href="bivariado-con-variables-categoricas.html#cb12-29" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;no&quot;</span> <span class="ot">=</span> <span class="st">&quot;#A7C7E7&quot;</span>, <span class="st">&quot;yes&quot;</span> <span class="ot">=</span> <span class="st">&quot;#A8E6A2&quot;</span>),</span>
<span id="cb12-30"><a href="bivariado-con-variables-categoricas.html#cb12-30" tabindex="-1"></a>    <span class="at">guide =</span> <span class="cn">FALSE</span>   <span class="co"># 🔹 Elimina la leyenda</span></span>
<span id="cb12-31"><a href="bivariado-con-variables-categoricas.html#cb12-31" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-32"><a href="bivariado-con-variables-categoricas.html#cb12-32" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb12-33"><a href="bivariado-con-variables-categoricas.html#cb12-33" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb12-34"><a href="bivariado-con-variables-categoricas.html#cb12-34" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),  <span class="co"># 🔹 Sin negrita</span></span>
<span id="cb12-35"><a href="bivariado-con-variables-categoricas.html#cb12-35" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb12-36"><a href="bivariado-con-variables-categoricas.html#cb12-36" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb12-37"><a href="bivariado-con-variables-categoricas.html#cb12-37" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb12-38"><a href="bivariado-con-variables-categoricas.html#cb12-38" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb12-39"><a href="bivariado-con-variables-categoricas.html#cb12-39" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Warning: The `guide` argument in `scale_*()` cannot be `FALSE`. This was deprecated in
## ggplot2 3.3.4.
## ℹ Please use &quot;none&quot; instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<p><img src="figs-parejo/unnamed-chunk-8-1.png" width="768" /></p>
<p><strong>Interpretación Job vs Y:</strong>
El análisis ocupacional revela patrones interesantes de comportamiento según el tipo de trabajo. Entre quienes respondieron afirmativamente (<code>yes</code>), las ocupaciones más representadas incluyen management, technician, y admin, seguidas por services y retired. En contraste, en el grupo de respuesta negativa (<code>no</code>), blue-collar workers, management, y technician dominan las categorías. Las ocupaciones como student, retired, y management muestran proporciones relativamente más altas de respuestas positivas, lo que sugiere que estos grupos pueden tener mayor estabilidad financiera o diferentes necesidades de inversión. Los trabajadores de cuello azul (blue-collar) tienden a rechazar más el producto, posiblemente debido a menores ingresos disponibles o diferentes prioridades financieras.</p>
<p>#marital vs y</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="bivariado-con-variables-categoricas.html#cb14-1" tabindex="-1"></a>data_plot <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="bivariado-con-variables-categoricas.html#cb14-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="bivariado-con-variables-categoricas.html#cb14-3" tabindex="-1"></a>  <span class="fu">count</span>(marital, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="bivariado-con-variables-categoricas.html#cb14-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> marital,</span>
<span id="cb14-5"><a href="bivariado-con-variables-categoricas.html#cb14-5" tabindex="-1"></a>         <span class="at">variable =</span> <span class="st">&quot;marital&quot;</span>,</span>
<span id="cb14-6"><a href="bivariado-con-variables-categoricas.html#cb14-6" tabindex="-1"></a>         <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-7"><a href="bivariado-con-variables-categoricas.html#cb14-7" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span>
<span id="cb14-8"><a href="bivariado-con-variables-categoricas.html#cb14-8" tabindex="-1"></a></span>
<span id="cb14-9"><a href="bivariado-con-variables-categoricas.html#cb14-9" tabindex="-1"></a>data_plot <span class="sc">%&gt;%</span> </span>
<span id="cb14-10"><a href="bivariado-con-variables-categoricas.html#cb14-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> categoria, <span class="at">y =</span> n, <span class="at">fill =</span> y)) <span class="sc">+</span></span>
<span id="cb14-11"><a href="bivariado-con-variables-categoricas.html#cb14-11" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>)) <span class="sc">+</span></span>
<span id="cb14-12"><a href="bivariado-con-variables-categoricas.html#cb14-12" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, <span class="fu">round</span>(porcentaje, <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)),</span>
<span id="cb14-13"><a href="bivariado-con-variables-categoricas.html#cb14-13" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb14-14"><a href="bivariado-con-variables-categoricas.html#cb14-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Estado civil (marital)&quot;</span>,</span>
<span id="cb14-15"><a href="bivariado-con-variables-categoricas.html#cb14-15" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Estado civil&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Cantidad de clientes&quot;</span>) <span class="sc">+</span></span>
<span id="cb14-16"><a href="bivariado-con-variables-categoricas.html#cb14-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb14-17"><a href="bivariado-con-variables-categoricas.html#cb14-17" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;no&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;yes&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>))</span></code></pre></div>
<p><img src="figs-parejo/unnamed-chunk-9-1.png" width="768" /></p>
<p><strong>Interpretación Marital vs Y:</strong>
La distribución del estado civil según la respuesta del marketing muestra diferencias relevantes en los patrones de respuesta. Entre quienes respondieron afirmativamente (<code>yes</code>), el 53.17% están casados, el 32.05% solteros y el 14.78% divorciados. En contraste, en el grupo que respondió negativamente (<code>no</code>), la mayoría (63%) también está casada, pero la proporción de solteros (25.73%) y divorciados (11.28%) es menor. Esta diferencia sugiere que las personas solteras y divorciadas presentan una mayor disposición o probabilidad de responder afirmativamente frente a la acción evaluada por la variable y, mientras que los casados tienden más a rechazarla, lo que podría ser clave para estrategias de segmentación o análisis de comportamiento.</p>
<p>#education vs y</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="bivariado-con-variables-categoricas.html#cb15-1" tabindex="-1"></a>data_plot <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="bivariado-con-variables-categoricas.html#cb15-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="bivariado-con-variables-categoricas.html#cb15-3" tabindex="-1"></a>  <span class="fu">count</span>(education, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="bivariado-con-variables-categoricas.html#cb15-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> education,</span>
<span id="cb15-5"><a href="bivariado-con-variables-categoricas.html#cb15-5" tabindex="-1"></a>         <span class="at">variable =</span> <span class="st">&quot;education&quot;</span>,</span>
<span id="cb15-6"><a href="bivariado-con-variables-categoricas.html#cb15-6" tabindex="-1"></a>         <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-7"><a href="bivariado-con-variables-categoricas.html#cb15-7" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span>
<span id="cb15-8"><a href="bivariado-con-variables-categoricas.html#cb15-8" tabindex="-1"></a></span>
<span id="cb15-9"><a href="bivariado-con-variables-categoricas.html#cb15-9" tabindex="-1"></a>data_plot <span class="sc">%&gt;%</span> </span>
<span id="cb15-10"><a href="bivariado-con-variables-categoricas.html#cb15-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> categoria, <span class="at">y =</span> n, <span class="at">fill =</span> y)) <span class="sc">+</span></span>
<span id="cb15-11"><a href="bivariado-con-variables-categoricas.html#cb15-11" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>)) <span class="sc">+</span></span>
<span id="cb15-12"><a href="bivariado-con-variables-categoricas.html#cb15-12" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, <span class="fu">round</span>(porcentaje, <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)),</span>
<span id="cb15-13"><a href="bivariado-con-variables-categoricas.html#cb15-13" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb15-14"><a href="bivariado-con-variables-categoricas.html#cb15-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Nivel educativo (education)&quot;</span>,</span>
<span id="cb15-15"><a href="bivariado-con-variables-categoricas.html#cb15-15" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Educación&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Cantidad de clientes&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-16"><a href="bivariado-con-variables-categoricas.html#cb15-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb15-17"><a href="bivariado-con-variables-categoricas.html#cb15-17" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;no&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;yes&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>))</span></code></pre></div>
<p><img src="figs-parejo/unnamed-chunk-10-1.png" width="768" /></p>
<p><strong>Interpretación Education vs Y:</strong>
La distribución educativa muestra que el nivel de educación influye significativamente en la respuesta al marketing. Entre quienes respondieron afirmativamente (<code>yes</code>), predominan los niveles secondary y tertiary, con una menor representación de primary y unknown. En el grupo de respuesta negativa (<code>no</code>), secondary education domina ampliamente, seguido por primary y tertiary. Los clientes con educación terciaria (universitaria) muestran una mayor propensión a aceptar el producto, lo que puede asociarse con mayores ingresos, mejor comprensión de productos financieros, y mayor capacidad de ahorro. Esto sugiere que las campañas dirigidas a segmentos con mayor educación podrían ser más efectivas.</p>
<p>#housing vs y</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="bivariado-con-variables-categoricas.html#cb16-1" tabindex="-1"></a>data_plot <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="bivariado-con-variables-categoricas.html#cb16-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="bivariado-con-variables-categoricas.html#cb16-3" tabindex="-1"></a>  <span class="fu">count</span>(housing, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="bivariado-con-variables-categoricas.html#cb16-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> housing,</span>
<span id="cb16-5"><a href="bivariado-con-variables-categoricas.html#cb16-5" tabindex="-1"></a>         <span class="at">variable =</span> <span class="st">&quot;housing&quot;</span>,</span>
<span id="cb16-6"><a href="bivariado-con-variables-categoricas.html#cb16-6" tabindex="-1"></a>         <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-7"><a href="bivariado-con-variables-categoricas.html#cb16-7" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span>
<span id="cb16-8"><a href="bivariado-con-variables-categoricas.html#cb16-8" tabindex="-1"></a></span>
<span id="cb16-9"><a href="bivariado-con-variables-categoricas.html#cb16-9" tabindex="-1"></a>data_plot <span class="sc">%&gt;%</span> </span>
<span id="cb16-10"><a href="bivariado-con-variables-categoricas.html#cb16-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> categoria, <span class="at">y =</span> n, <span class="at">fill =</span> y)) <span class="sc">+</span></span>
<span id="cb16-11"><a href="bivariado-con-variables-categoricas.html#cb16-11" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>)) <span class="sc">+</span></span>
<span id="cb16-12"><a href="bivariado-con-variables-categoricas.html#cb16-12" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, <span class="fu">round</span>(porcentaje, <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)),</span>
<span id="cb16-13"><a href="bivariado-con-variables-categoricas.html#cb16-13" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb16-14"><a href="bivariado-con-variables-categoricas.html#cb16-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Préstamo de vivienda (housing)&quot;</span>,</span>
<span id="cb16-15"><a href="bivariado-con-variables-categoricas.html#cb16-15" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Housing&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Cantidad de clientes&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-16"><a href="bivariado-con-variables-categoricas.html#cb16-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb16-17"><a href="bivariado-con-variables-categoricas.html#cb16-17" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;no&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;yes&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>))</span></code></pre></div>
<p><img src="figs-parejo/unnamed-chunk-11-1.png" width="768" /></p>
<p><strong>Interpretación Housing vs Y:</strong>
El análisis del préstamo de vivienda revela un patrón interesante en el comportamiento financiero. Entre quienes respondieron afirmativamente (<code>yes</code>), aproximadamente el 55-60% no tiene préstamo de vivienda, mientras que el 40-45% sí lo tiene. En el grupo de respuesta negativa (<code>no</code>), la proporción es similar pero con una ligera tendencia hacia tener préstamo de vivienda. Los clientes sin préstamo hipotecario muestran una mayor disposición a contratar el depósito a plazo, posiblemente porque tienen mayor liquidez disponible al no tener la carga de una hipoteca, lo que les permite considerar productos de ahorro e inversión.</p>
<p>#loan vs y</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="bivariado-con-variables-categoricas.html#cb17-1" tabindex="-1"></a>data_plot <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="bivariado-con-variables-categoricas.html#cb17-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="bivariado-con-variables-categoricas.html#cb17-3" tabindex="-1"></a>  <span class="fu">count</span>(loan, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="bivariado-con-variables-categoricas.html#cb17-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> loan,</span>
<span id="cb17-5"><a href="bivariado-con-variables-categoricas.html#cb17-5" tabindex="-1"></a>         <span class="at">variable =</span> <span class="st">&quot;loan&quot;</span>,</span>
<span id="cb17-6"><a href="bivariado-con-variables-categoricas.html#cb17-6" tabindex="-1"></a>         <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="bivariado-con-variables-categoricas.html#cb17-7" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span>
<span id="cb17-8"><a href="bivariado-con-variables-categoricas.html#cb17-8" tabindex="-1"></a></span>
<span id="cb17-9"><a href="bivariado-con-variables-categoricas.html#cb17-9" tabindex="-1"></a>data_plot <span class="sc">%&gt;%</span> </span>
<span id="cb17-10"><a href="bivariado-con-variables-categoricas.html#cb17-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> categoria, <span class="at">y =</span> n, <span class="at">fill =</span> y)) <span class="sc">+</span></span>
<span id="cb17-11"><a href="bivariado-con-variables-categoricas.html#cb17-11" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>)) <span class="sc">+</span></span>
<span id="cb17-12"><a href="bivariado-con-variables-categoricas.html#cb17-12" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, <span class="fu">round</span>(porcentaje, <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)),</span>
<span id="cb17-13"><a href="bivariado-con-variables-categoricas.html#cb17-13" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb17-14"><a href="bivariado-con-variables-categoricas.html#cb17-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Préstamo personal (loan)&quot;</span>,</span>
<span id="cb17-15"><a href="bivariado-con-variables-categoricas.html#cb17-15" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Loan&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Cantidad de clientes&quot;</span>) <span class="sc">+</span></span>
<span id="cb17-16"><a href="bivariado-con-variables-categoricas.html#cb17-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb17-17"><a href="bivariado-con-variables-categoricas.html#cb17-17" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;no&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;yes&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>))</span></code></pre></div>
<p><img src="figs-parejo/unnamed-chunk-12-1.png" width="768" /></p>
<p><strong>Interpretación Loan vs Y:</strong>
La variable de préstamo personal presenta un patrón muy claro y significativo. Entre quienes respondieron afirmativamente (<code>yes</code>), la gran mayoría (&gt;85%) no tiene préstamos personales, mientras que menos del 15% sí los tiene. Esta tendencia es aún más marcada que con los préstamos hipotecarios. En el grupo de respuesta negativa (<code>no</code>), también predominan quienes no tienen préstamos personales, pero la proporción de quienes sí los tienen es mayor. Los clientes sin préstamos personales muestran una clara mayor predisposición a contratar el depósito a plazo, lo que indica que la ausencia de deudas de consumo se asocia con mayor capacidad de ahorro y mejor disposición hacia productos de inversión.</p>
<p>#contact vs y</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="bivariado-con-variables-categoricas.html#cb18-1" tabindex="-1"></a>data_plot <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="bivariado-con-variables-categoricas.html#cb18-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="bivariado-con-variables-categoricas.html#cb18-3" tabindex="-1"></a>  <span class="fu">count</span>(contact, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="bivariado-con-variables-categoricas.html#cb18-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> contact,</span>
<span id="cb18-5"><a href="bivariado-con-variables-categoricas.html#cb18-5" tabindex="-1"></a>         <span class="at">variable =</span> <span class="st">&quot;contact&quot;</span>,</span>
<span id="cb18-6"><a href="bivariado-con-variables-categoricas.html#cb18-6" tabindex="-1"></a>         <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="bivariado-con-variables-categoricas.html#cb18-7" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span>
<span id="cb18-8"><a href="bivariado-con-variables-categoricas.html#cb18-8" tabindex="-1"></a></span>
<span id="cb18-9"><a href="bivariado-con-variables-categoricas.html#cb18-9" tabindex="-1"></a>data_plot <span class="sc">%&gt;%</span> </span>
<span id="cb18-10"><a href="bivariado-con-variables-categoricas.html#cb18-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> categoria, <span class="at">y =</span> n, <span class="at">fill =</span> y)) <span class="sc">+</span></span>
<span id="cb18-11"><a href="bivariado-con-variables-categoricas.html#cb18-11" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>)) <span class="sc">+</span></span>
<span id="cb18-12"><a href="bivariado-con-variables-categoricas.html#cb18-12" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, <span class="fu">round</span>(porcentaje, <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)),</span>
<span id="cb18-13"><a href="bivariado-con-variables-categoricas.html#cb18-13" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb18-14"><a href="bivariado-con-variables-categoricas.html#cb18-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Tipo de contacto (contact)&quot;</span>,</span>
<span id="cb18-15"><a href="bivariado-con-variables-categoricas.html#cb18-15" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Tipo de contacto&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Cantidad de clientes&quot;</span>) <span class="sc">+</span></span>
<span id="cb18-16"><a href="bivariado-con-variables-categoricas.html#cb18-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb18-17"><a href="bivariado-con-variables-categoricas.html#cb18-17" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;no&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;yes&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>))</span></code></pre></div>
<p><img src="figs-parejo/unnamed-chunk-13-1.png" width="768" /></p>
<p><strong>Interpretación Contact vs Y:</strong>
El análisis del tipo de contacto revela la efectividad de los diferentes canales de comunicación. Entre quienes respondieron afirmativamente (<code>yes</code>), el contacto cellular (móvil) representa la gran mayoría, mientras que telephone y unknown tienen participaciones menores. En el grupo de respuesta negativa (<code>no</code>), también domina el contacto cellular, pero con proporciones ligeramente diferentes. El contacto por teléfono móvil muestra ser el canal más efectivo, posiblemente porque permite mayor accesibilidad y conveniencia para los clientes. Esto sugiere que las estrategias de marketing deberían priorizar el contacto móvil para optimizar las tasas de conversión.</p>
<p>#poutcome vs y</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="bivariado-con-variables-categoricas.html#cb19-1" tabindex="-1"></a>data_plot <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="bivariado-con-variables-categoricas.html#cb19-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="bivariado-con-variables-categoricas.html#cb19-3" tabindex="-1"></a>  <span class="fu">count</span>(poutcome, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="bivariado-con-variables-categoricas.html#cb19-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria =</span> poutcome,</span>
<span id="cb19-5"><a href="bivariado-con-variables-categoricas.html#cb19-5" tabindex="-1"></a>         <span class="at">variable =</span> <span class="st">&quot;poutcome&quot;</span>,</span>
<span id="cb19-6"><a href="bivariado-con-variables-categoricas.html#cb19-6" tabindex="-1"></a>         <span class="at">porcentaje =</span> (n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="bivariado-con-variables-categoricas.html#cb19-7" tabindex="-1"></a>  <span class="fu">select</span>(y, categoria, n, porcentaje)</span>
<span id="cb19-8"><a href="bivariado-con-variables-categoricas.html#cb19-8" tabindex="-1"></a></span>
<span id="cb19-9"><a href="bivariado-con-variables-categoricas.html#cb19-9" tabindex="-1"></a>data_plot <span class="sc">%&gt;%</span> </span>
<span id="cb19-10"><a href="bivariado-con-variables-categoricas.html#cb19-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> categoria, <span class="at">y =</span> n, <span class="at">fill =</span> y)) <span class="sc">+</span></span>
<span id="cb19-11"><a href="bivariado-con-variables-categoricas.html#cb19-11" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>)) <span class="sc">+</span></span>
<span id="cb19-12"><a href="bivariado-con-variables-categoricas.html#cb19-12" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, <span class="fu">round</span>(porcentaje, <span class="dv">1</span>), <span class="st">&quot;%)&quot;</span>)),</span>
<span id="cb19-13"><a href="bivariado-con-variables-categoricas.html#cb19-13" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb19-14"><a href="bivariado-con-variables-categoricas.html#cb19-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Resultado de campaña previa (poutcome)&quot;</span>,</span>
<span id="cb19-15"><a href="bivariado-con-variables-categoricas.html#cb19-15" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Poutcome&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Cantidad de clientes&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-16"><a href="bivariado-con-variables-categoricas.html#cb19-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb19-17"><a href="bivariado-con-variables-categoricas.html#cb19-17" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;no&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;yes&quot;</span> <span class="ot">=</span> <span class="st">&quot;lightgreen&quot;</span>))</span></code></pre></div>
<p><img src="figs-parejo/unnamed-chunk-14-1.png" width="768" /></p>
<p><strong>Interpretación Poutcome vs Y:</strong>
El resultado de campañas previas es un predictor extremadamente relevante del comportamiento futuro. Entre quienes respondieron afirmativamente (<code>yes</code>), predominan claramente los casos de success y unknown, con muy pocos casos de failure. En contraste, en el grupo de respuesta negativa (<code>no</code>), domina abrumadoramente la categoría unknown, seguida por failure, con muy pocos casos de success. Los clientes con historial de éxito en campañas anteriores muestran una probabilidad significativamente mayor de volver a responder positivamente, mientras que aquellos con historial de failure tienden a rechazar ofertas futuras. Esta variable debería ser fundamental para la segmentación y priorización de contactos en futuras campañas.</p>
<div id="tecnicas-inferenciales-entre-las-variables-cuantitativas-y-la-variable-objetivo" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Tecnicas inferenciales entre las variables cuantitativas y la variable objetivo<a href="bivariado-con-variables-categoricas.html#tecnicas-inferenciales-entre-las-variables-cuantitativas-y-la-variable-objetivo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A continuacion se realizan pruebas de comparacion de medias entre dos grupos
independientes, sabemos que no hay dependencia entre los grupos por lo que no
haremos pruebas para pareados. Para llevar a cabo dichas pruebas, se deben
confirmar unos supuestos previamente:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="bivariado-con-variables-categoricas.html#cb20-1" tabindex="-1"></a>datos <span class="ot">&lt;-</span> data</span>
<span id="cb20-2"><a href="bivariado-con-variables-categoricas.html#cb20-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb20-3"><a href="bivariado-con-variables-categoricas.html#cb20-3" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb20-4"><a href="bivariado-con-variables-categoricas.html#cb20-4" tabindex="-1"></a>df_y_yes <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb20-5"><a href="bivariado-con-variables-categoricas.html#cb20-5" tabindex="-1"></a>  <span class="fu">filter</span>(y <span class="sc">==</span> <span class="st">&quot;yes&quot;</span>)</span>
<span id="cb20-6"><a href="bivariado-con-variables-categoricas.html#cb20-6" tabindex="-1"></a>df_y_no <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span> </span>
<span id="cb20-7"><a href="bivariado-con-variables-categoricas.html#cb20-7" tabindex="-1"></a>  <span class="fu">filter</span>(y <span class="sc">==</span> <span class="st">&quot;no&quot;</span>)</span></code></pre></div>
<p><strong>balance - y:</strong></p>
<p>Por medio de la prueba de normalidad de Kolmogorov - Smirnov verificamos
que los datos de ambas muestras presenten un comportamiento normal.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="bivariado-con-variables-categoricas.html#cb21-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="bivariado-con-variables-categoricas.html#cb21-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="bivariado-con-variables-categoricas.html#cb21-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(balance),</span>
<span id="cb21-4"><a href="bivariado-con-variables-categoricas.html#cb21-4" tabindex="-1"></a>            <span class="at">est_ks =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(balance),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>statistic,</span>
<span id="cb21-5"><a href="bivariado-con-variables-categoricas.html#cb21-5" tabindex="-1"></a>            <span class="at">p_ks =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(balance),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>p.value,</span>
<span id="cb21-6"><a href="bivariado-con-variables-categoricas.html#cb21-6" tabindex="-1"></a>            <span class="at">estsw =</span> <span class="fu">shapiro.test</span>(balance)<span class="sc">$</span>statistic,</span>
<span id="cb21-7"><a href="bivariado-con-variables-categoricas.html#cb21-7" tabindex="-1"></a>            <span class="at">p_sw =</span> <span class="fu">shapiro.test</span>(balance)<span class="sc">$</span>p.value,</span>
<span id="cb21-8"><a href="bivariado-con-variables-categoricas.html#cb21-8" tabindex="-1"></a>            <span class="at">est_lt =</span> <span class="fu">lillie.test</span>(balance)<span class="sc">$</span>statistic,</span>
<span id="cb21-9"><a href="bivariado-con-variables-categoricas.html#cb21-9" tabindex="-1"></a>            <span class="at">p_lt =</span> <span class="fu">lillie.test</span>(balance)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## Warning: There were 4 warnings in `summarise()`.
## The first warning was:
## ℹ In argument: `est_ks = ks.test(scale(balance), &quot;pnorm&quot;)$statistic`.
## ℹ In group 1: `y = no`.
## Caused by warning in `ks.test.default()`:
## ! ties should not be present for the one-sample Kolmogorov-Smirnov test
## ℹ Run `dplyr::last_dplyr_warnings()` to see the 3 remaining warnings.</code></pre>
<pre><code>## # A tibble: 2 × 8
##   y         n est_ks      p_ks estsw     p_sw est_lt     p_lt
##   &lt;fct&gt; &lt;int&gt;  &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
## 1 no     4000  0.257 1.37e-229 0.487 2.18e-75  0.257 0       
## 2 yes     521  0.203 4.37e- 19 0.651 3.08e-31  0.203 8.84e-60</code></pre>
<p>Aplicando las pruebas de lillie.test, Kolmogorov-Smirnov y Shapiro-Wilk
podemos evidenciar que los datos de la categoria numerica <span class="math inline">\(balance\)</span> no presentan
normalidad en ninguno de los dos grupos, esto se concluye a partir de los <strong>p-valores</strong>
observados, donde todos son notoriamente inferiores a 0.05.
Por eso, procedemos a usar Wilcoxon rank-sum test o U-test de Mann-Whitney;
en este contexto, se recomienda emplear el test de Levene o el test no paramétrico de Fligner-Killeen,
ambos diseñados para evaluar la homogeneidad de varianzas y que utilizan la mediana como medida de tendencia central,
lo que los hace adecuados en presencia de datos no normales.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="bivariado-con-variables-categoricas.html#cb24-1" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## 
## Attaching package: &#39;car&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     recode</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     some</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="bivariado-con-variables-categoricas.html#cb29-1" tabindex="-1"></a><span class="fu">leveneTest</span>(balance <span class="sc">~</span> y, <span class="at">data =</span> datos, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##         Df F value Pr(&gt;F)
## group    1  0.1056 0.7452
##       4519</code></pre>
<p>La prueba de Levene nos indica que no se encuentran diferencias significativas
en la varianza del saldo promedio anual de la cuenta bancaria entre los grupos <span class="math inline">\((F_{(1)} = 0.1056, \; p\text{-}valor = 0.7452)\)</span>.
Ahora comprobemos si hay diferencia entre los grupos:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="bivariado-con-variables-categoricas.html#cb31-1" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;rstatix&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="bivariado-con-variables-categoricas.html#cb34-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="bivariado-con-variables-categoricas.html#cb34-2" tabindex="-1"></a>  <span class="fu">wilcox_test</span>(balance <span class="sc">~</span> y, </span>
<span id="cb34-3"><a href="bivariado-con-variables-categoricas.html#cb34-3" tabindex="-1"></a>              <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.     group1 group2    n1    n2 statistic          p
## * &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 balance no     yes     4000   521   893230. 0.00000011</code></pre>
<p>La prueba de U de Mann-Whitney, nos muestra que hay evidencia
estadísticamente significativa de una diferencia en el saldo promedio anual de
la cuenta bancaria entre los clientes que aceptan y los que no aceptan contratar
un deposito a plazo fijo <span class="math inline">\((U = 893230, \; p\text{-}valor = 0.00000011)\)</span>.</p>
<p><strong>age - y</strong></p>
<p>Por medio de la prueba de normalidad de Kolmogorov - Smirnov verificamos
que los datos de ambas muestras presenten un comportamiento normal.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="bivariado-con-variables-categoricas.html#cb36-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="bivariado-con-variables-categoricas.html#cb36-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="bivariado-con-variables-categoricas.html#cb36-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n2 =</span> <span class="fu">length</span>(age),</span>
<span id="cb36-4"><a href="bivariado-con-variables-categoricas.html#cb36-4" tabindex="-1"></a>            <span class="at">est_ks2 =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(age),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>statistic,</span>
<span id="cb36-5"><a href="bivariado-con-variables-categoricas.html#cb36-5" tabindex="-1"></a>            <span class="at">p_ks2 =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(age),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>p.value,</span>
<span id="cb36-6"><a href="bivariado-con-variables-categoricas.html#cb36-6" tabindex="-1"></a>            <span class="at">estsw2 =</span> <span class="fu">shapiro.test</span>(age)<span class="sc">$</span>statistic,</span>
<span id="cb36-7"><a href="bivariado-con-variables-categoricas.html#cb36-7" tabindex="-1"></a>            <span class="at">p_sw2 =</span> <span class="fu">shapiro.test</span>(age)<span class="sc">$</span>p.value,</span>
<span id="cb36-8"><a href="bivariado-con-variables-categoricas.html#cb36-8" tabindex="-1"></a>            <span class="at">est_lt2 =</span> <span class="fu">lillie.test</span>(age)<span class="sc">$</span>statistic,</span>
<span id="cb36-9"><a href="bivariado-con-variables-categoricas.html#cb36-9" tabindex="-1"></a>            <span class="at">p_lt2 =</span> <span class="fu">lillie.test</span>(age)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## Warning: There were 4 warnings in `summarise()`.
## The first warning was:
## ℹ In argument: `est_ks2 = ks.test(scale(age), &quot;pnorm&quot;)$statistic`.
## ℹ In group 1: `y = no`.
## Caused by warning in `ks.test.default()`:
## ! ties should not be present for the one-sample Kolmogorov-Smirnov test
## ℹ Run `dplyr::last_dplyr_warnings()` to see the 3 remaining warnings.</code></pre>
<pre><code>## # A tibble: 2 × 8
##   y        n2 est_ks2    p_ks2 estsw2    p_sw2 est_lt2    p_lt2
##   &lt;fct&gt; &lt;int&gt;   &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
## 1 no     4000  0.0951 7.33e-32  0.963 6.98e-31  0.0951 2.59e-98
## 2 yes     521  0.112  4.29e- 6  0.944 4.44e-13  0.112  3.53e-17</code></pre>
<p>Aplicando las pruebas de lillie.test, Kolmogorov-Smirnov y Shapiro-Wilk
podemos evidenciar que los datos de la categoria numerica <span class="math inline">\(age\)</span> no presentan
normalidad en ninguno de los dos grupos, esto se concluye a partir de los <strong>p-valores</strong>
observados, donde todos son notoriamente inferiores a 0.05 como en la categoria <span class="math inline">\(balance\)</span> analizada anteriormente.
Por eso, procedemos a usar Wilcoxon rank-sum test o U-test de Mann-Whitney;
en este contexto, se recomienda emplear el test de Levene.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="bivariado-con-variables-categoricas.html#cb39-1" tabindex="-1"></a><span class="fu">leveneTest</span>(age <span class="sc">~</span> y, <span class="at">data =</span> datos, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##         Df F value    Pr(&gt;F)    
## group    1  50.677 1.261e-12 ***
##       4519                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene nos muestra que existen diferencias significativas
en la varianza de las edades de los usuarios entre los grupos <span class="math inline">\((F_{(1)} = 50.677, \; p\text{-}valor = 1.261e-12)\)</span>.
Ahora comprobemos si hay diferencia entre los grupos, dado que no se requiere
normalidad ni homocedasticidad estricta, usaremos U-test de Mann-Whitney:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="bivariado-con-variables-categoricas.html#cb41-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="bivariado-con-variables-categoricas.html#cb41-2" tabindex="-1"></a>  <span class="fu">wilcox_test</span>(age <span class="sc">~</span> y, </span>
<span id="cb41-3"><a href="bivariado-con-variables-categoricas.html#cb41-3" tabindex="-1"></a>              <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.   group1 group2    n1    n2 statistic     p
## * &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1 age   no     yes     4000   521   1011360 0.274</code></pre>
<p>La prueba de U de Mann-Whitney, nos muestra que no hay evidencia estadísticamente
significativa de una diferencia en la edad de los usuarios entre el grupo que acepta
y el que no acepta contratar un deposito a plazo fijo <span class="math inline">\((U = 1011360, \; p\text{-}valor = 0.274)\)</span>.</p>
<p><strong>duration - y</strong></p>
<p>Por medio de la prueba de normalidad de Kolmogorov - Smirnov verificamos
que los datos de ambas muestras presenten un comportamiento normal.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="bivariado-con-variables-categoricas.html#cb43-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="bivariado-con-variables-categoricas.html#cb43-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="bivariado-con-variables-categoricas.html#cb43-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n3 =</span> <span class="fu">length</span>(duration),</span>
<span id="cb43-4"><a href="bivariado-con-variables-categoricas.html#cb43-4" tabindex="-1"></a>            <span class="at">est_ks3 =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(duration),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>statistic,</span>
<span id="cb43-5"><a href="bivariado-con-variables-categoricas.html#cb43-5" tabindex="-1"></a>            <span class="at">p_ks3 =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(duration),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>p.value,</span>
<span id="cb43-6"><a href="bivariado-con-variables-categoricas.html#cb43-6" tabindex="-1"></a>            <span class="at">estsw3 =</span> <span class="fu">shapiro.test</span>(duration)<span class="sc">$</span>statistic,</span>
<span id="cb43-7"><a href="bivariado-con-variables-categoricas.html#cb43-7" tabindex="-1"></a>            <span class="at">p_sw3 =</span> <span class="fu">shapiro.test</span>(duration)<span class="sc">$</span>p.value,</span>
<span id="cb43-8"><a href="bivariado-con-variables-categoricas.html#cb43-8" tabindex="-1"></a>            <span class="at">est_lt3 =</span> <span class="fu">lillie.test</span>(duration)<span class="sc">$</span>statistic,</span>
<span id="cb43-9"><a href="bivariado-con-variables-categoricas.html#cb43-9" tabindex="-1"></a>            <span class="at">p_lt3 =</span> <span class="fu">lillie.test</span>(duration)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## Warning: There were 4 warnings in `summarise()`.
## The first warning was:
## ℹ In argument: `est_ks3 = ks.test(scale(duration), &quot;pnorm&quot;)$statistic`.
## ℹ In group 1: `y = no`.
## Caused by warning in `ks.test.default()`:
## ! ties should not be present for the one-sample Kolmogorov-Smirnov test
## ℹ Run `dplyr::last_dplyr_warnings()` to see the 3 remaining warnings.</code></pre>
<pre><code>## # A tibble: 2 × 8
##   y        n3 est_ks3    p_ks3 estsw3    p_sw3 est_lt3     p_lt3
##   &lt;fct&gt; &lt;int&gt;   &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;
## 1 no     4000   0.157 6.09e-86  0.758 1.29e-60   0.157 2.23e-274
## 2 yes     521   0.115 2.02e- 6  0.874 3.99e-20   0.115 3.15e- 18</code></pre>
<p>Empleando las pruebas de lillie.test, Kolmogorov-Smirnov y Shapiro-Wilk
podemos notar que los datos de la categoria numerica <span class="math inline">\(duration\)</span> tampoco presentan
normalidad en ninguno de los dos grupos, esto se concluye a partir de los <strong>p-valores</strong>
observados, donde todos son notoriamente inferiores a 0.05 como en la categoria <span class="math inline">\(balance\)</span> y <span class="math inline">\(age\)</span> analizadas previamente.
A continuacion, procedemos a usar Wilcoxon rank-sum test o U-test de Mann-Whitney;
en este contexto, se recomienda emplear el test de Levene.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="bivariado-con-variables-categoricas.html#cb46-1" tabindex="-1"></a><span class="fu">leveneTest</span>(duration <span class="sc">~</span> y, <span class="at">data =</span> datos, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##         Df F value    Pr(&gt;F)    
## group    1  310.43 &lt; 2.2e-16 ***
##       4519                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene señala que existen diferencias significativas
en la varianza de las duraciones de la ultima llamada entre los grupos <span class="math inline">\((F_{(1)} = 310.43, \; p\text{-}valor &lt; 2.2e-16)\)</span>.
Verifiquemos si hay diferencia entre los grupos; debido a que no hay normalidad
ni homocedasticidad, usaremos U-test de Mann-Whitney:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="bivariado-con-variables-categoricas.html#cb48-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="bivariado-con-variables-categoricas.html#cb48-2" tabindex="-1"></a>  <span class="fu">wilcox_test</span>(duration <span class="sc">~</span> y, </span>
<span id="cb48-3"><a href="bivariado-con-variables-categoricas.html#cb48-3" tabindex="-1"></a>              <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.      group1 group2    n1    n2 statistic         p
## * &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 duration no     yes     4000   521    385525 2.33e-121</code></pre>
<p>La prueba de U de Mann-Whitney, nos muestra que hay evidencia
estadísticamente significativa de una diferencia en la duracion de la ultima
llamada entre los clientes que aceptan y los que no aceptan contratar
un deposito a plazo fijo <span class="math inline">\((U = 385525, \; p\text{-}valor = 2.33e-121)\)</span>.</p>
<p><strong>campaign - y</strong></p>
<p>Veamos si los datos presentan comportamiento normal:</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="bivariado-con-variables-categoricas.html#cb50-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="bivariado-con-variables-categoricas.html#cb50-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="bivariado-con-variables-categoricas.html#cb50-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n4 =</span> <span class="fu">length</span>(campaign),</span>
<span id="cb50-4"><a href="bivariado-con-variables-categoricas.html#cb50-4" tabindex="-1"></a>            <span class="at">est_ks4 =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(campaign),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>statistic,</span>
<span id="cb50-5"><a href="bivariado-con-variables-categoricas.html#cb50-5" tabindex="-1"></a>            <span class="at">p_ks4 =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(campaign),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>p.value,</span>
<span id="cb50-6"><a href="bivariado-con-variables-categoricas.html#cb50-6" tabindex="-1"></a>            <span class="at">estsw4 =</span> <span class="fu">shapiro.test</span>(campaign)<span class="sc">$</span>statistic,</span>
<span id="cb50-7"><a href="bivariado-con-variables-categoricas.html#cb50-7" tabindex="-1"></a>            <span class="at">p_sw4 =</span> <span class="fu">shapiro.test</span>(campaign)<span class="sc">$</span>p.value,</span>
<span id="cb50-8"><a href="bivariado-con-variables-categoricas.html#cb50-8" tabindex="-1"></a>            <span class="at">est_lt4 =</span> <span class="fu">lillie.test</span>(campaign)<span class="sc">$</span>statistic,</span>
<span id="cb50-9"><a href="bivariado-con-variables-categoricas.html#cb50-9" tabindex="-1"></a>            <span class="at">p_lt4 =</span> <span class="fu">lillie.test</span>(campaign)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## Warning: There were 4 warnings in `summarise()`.
## The first warning was:
## ℹ In argument: `est_ks4 = ks.test(scale(campaign), &quot;pnorm&quot;)$statistic`.
## ℹ In group 1: `y = no`.
## Caused by warning in `ks.test.default()`:
## ! ties should not be present for the one-sample Kolmogorov-Smirnov test
## ℹ Run `dplyr::last_dplyr_warnings()` to see the 3 remaining warnings.</code></pre>
<pre><code>## # A tibble: 2 × 8
##   y        n4 est_ks4     p_ks4 estsw4    p_sw4 est_lt4     p_lt4
##   &lt;fct&gt; &lt;int&gt;   &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;
## 1 no     4000   0.281 6.73e-275  0.563 4.32e-72   0.281 0        
## 2 yes     521   0.276 5.78e- 35  0.601 6.93e-33   0.276 5.63e-113</code></pre>
<p>A partir de las pruebas de Lilliefors (lillie.test), Kolmogorov-Smirnov y
Shapiro-Wilk, se observa que la variable numérica <span class="math inline">\(campaign\)</span> tampoco sigue
una distribución normal en ninguno de los dos grupos analizados. Esta
conclusión se fundamenta en los <strong>p-valores</strong> obtenidos, los cuales son
consistentemente menores a 0.05, al igual que lo evidenciado previamente en las
variables <span class="math inline">\(balance\)</span>, <span class="math inline">\(age\)</span> y <span class="math inline">\(duration\)</span>.
Por consiguiente, se procede a aplicar la prueba de Wilcoxon rank-sum o
U de Mann-Whitney. Se recomienda además utilizar la prueba
de Levene para evaluar la homogeneidad de varianzas.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="bivariado-con-variables-categoricas.html#cb53-1" tabindex="-1"></a><span class="fu">leveneTest</span>(campaign <span class="sc">~</span> y, <span class="at">data =</span> datos, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##         Df F value   Pr(&gt;F)   
## group    1  10.418 0.001257 **
##       4519                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene indica que existen diferencias significativas en la varianza
de la variable <span class="math inline">\(campaign\)</span> (numero de contactos realizados durante la campaña actual)
entre los grupos analizados <span class="math inline">\((F_{(1)} = 10.418, \; p\text{-}valor = 0.001257)\)</span>.
Dado que los datos no cumplen con los supuestos de normalidad ni de homocedasticidad,
se procederá a aplicar la prueba U de Mann-Whitney para verificar si existen
diferencias significativas entre los grupos.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="bivariado-con-variables-categoricas.html#cb55-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb55-2"><a href="bivariado-con-variables-categoricas.html#cb55-2" tabindex="-1"></a>  <span class="fu">wilcox_test</span>(campaign <span class="sc">~</span> y, </span>
<span id="cb55-3"><a href="bivariado-con-variables-categoricas.html#cb55-3" tabindex="-1"></a>              <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.      group1 group2    n1    n2 statistic        p
## * &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 campaign no     yes     4000   521  1158722. 0.000014</code></pre>
<p>La prueba de U de Mann-Whitney, nos muestra que hay evidencia estadísticamente
significativa de una diferencia en el numero de contactos realizados durante la
campaña actual entre los clientes que aceptan y los que no aceptan contratar
un deposito a plazo fijo <span class="math inline">\((U = 1158722, \; p\text{-}valor = 0.000014)\)</span>.</p>
<p><strong>pdays - y</strong></p>
<p>Comprobamos primeramente la normalidad de los datos de ambos grupos:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="bivariado-con-variables-categoricas.html#cb57-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="bivariado-con-variables-categoricas.html#cb57-2" tabindex="-1"></a>  <span class="fu">group_by</span>(y) <span class="sc">%&gt;%</span></span>
<span id="cb57-3"><a href="bivariado-con-variables-categoricas.html#cb57-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n5 =</span> <span class="fu">length</span>(pdays),</span>
<span id="cb57-4"><a href="bivariado-con-variables-categoricas.html#cb57-4" tabindex="-1"></a>            <span class="at">est_ks5 =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(pdays),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>statistic,</span>
<span id="cb57-5"><a href="bivariado-con-variables-categoricas.html#cb57-5" tabindex="-1"></a>            <span class="at">p_ks5 =</span> <span class="fu">ks.test</span>(<span class="fu">scale</span>(pdays),<span class="st">&#39;pnorm&#39;</span>)<span class="sc">$</span>p.value,</span>
<span id="cb57-6"><a href="bivariado-con-variables-categoricas.html#cb57-6" tabindex="-1"></a>            <span class="at">estsw5 =</span> <span class="fu">shapiro.test</span>(pdays)<span class="sc">$</span>statistic,</span>
<span id="cb57-7"><a href="bivariado-con-variables-categoricas.html#cb57-7" tabindex="-1"></a>            <span class="at">p_sw5 =</span> <span class="fu">shapiro.test</span>(pdays)<span class="sc">$</span>p.value,</span>
<span id="cb57-8"><a href="bivariado-con-variables-categoricas.html#cb57-8" tabindex="-1"></a>            <span class="at">est_lt5 =</span> <span class="fu">lillie.test</span>(pdays)<span class="sc">$</span>statistic,</span>
<span id="cb57-9"><a href="bivariado-con-variables-categoricas.html#cb57-9" tabindex="-1"></a>            <span class="at">p_lt5 =</span> <span class="fu">lillie.test</span>(pdays)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>## Warning: There were 4 warnings in `summarise()`.
## The first warning was:
## ℹ In argument: `est_ks5 = ks.test(scale(pdays), &quot;pnorm&quot;)$statistic`.
## ℹ In group 1: `y = no`.
## Caused by warning in `ks.test.default()`:
## ! ties should not be present for the one-sample Kolmogorov-Smirnov test
## ℹ Run `dplyr::last_dplyr_warnings()` to see the 3 remaining warnings.</code></pre>
<pre><code>## # A tibble: 2 × 8
##   y        n5 est_ks5    p_ks5 estsw5    p_sw5 est_lt5     p_lt5
##   &lt;fct&gt; &lt;int&gt;   &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;
## 1 no     4000   0.492 0         0.440 3.28e-77   0.492 0        
## 2 yes     521   0.363 5.34e-60  0.640 1.28e-31   0.363 1.06e-197</code></pre>
<p>De acuerdo con los resultados de las pruebas de Lilliefors (lillie.test),
Kolmogorov-Smirnov y Shapiro-Wilk, la variable numérica <span class="math inline">\(pdays\)</span>
tampoco presenta una distribución normal en ninguno de los grupos analizados.
Esta conclusión se basa en los <strong>p-valores</strong>, los cuales son menores a 0.05
en todos los casos, tal como se observó previamente en las variables <span class="math inline">\(balance\)</span>,
<span class="math inline">\(age\)</span>, <span class="math inline">\(duration\)</span> y <span class="math inline">\(campaign\)</span>.
En consecuencia, se opta por aplicar la prueba U de Mann-Whitney.
Además, se sugiere emplear la prueba de Levene para verificar la homogeneidad
de las varianzas.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="bivariado-con-variables-categoricas.html#cb60-1" tabindex="-1"></a><span class="fu">leveneTest</span>(pdays <span class="sc">~</span> y, <span class="at">data =</span> datos, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##         Df F value    Pr(&gt;F)    
## group    1  49.495 2.287e-12 ***
##       4519                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La prueba de Levene indica que existen diferencias significativas en la varianza
de la variable <span class="math inline">\(pdays\)</span> (numero de días transcurridos desde el último contacto previo)
entre los grupos analizados <span class="math inline">\((F_{(1)} = 49.495, \; p\text{-}valor = 2.287e-12)\)</span>.
Dado que los datos no cumplen con los supuestos de normalidad ni de homocedasticidad,
se procederá a aplicar la prueba U de Mann-Whitney para verificar si existen
diferencias significativas entre los grupos.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="bivariado-con-variables-categoricas.html#cb62-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="bivariado-con-variables-categoricas.html#cb62-2" tabindex="-1"></a>  <span class="fu">wilcox_test</span>(pdays <span class="sc">~</span> y, </span>
<span id="cb62-3"><a href="bivariado-con-variables-categoricas.html#cb62-3" tabindex="-1"></a>              <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 7
##   .y.   group1 group2    n1    n2 statistic        p
## * &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 pdays no     yes     4000   521    852275 5.72e-24</code></pre>
<p>La prueba de U de Mann-Whitney, nos muestra que hay evidencia estadísticamente
significativa de una diferencia en el numero de dias transcurridos desde el
ultimo contacto previo entre los clientes que aceptan y los que no aceptan contratar
un deposito a plazo fijo <span class="math inline">\((U = 852275, \; p\text{-}valor = 5.72e-24)\)</span>.</p>
<p><strong>Conclusion</strong></p>
<p>Resumiendo la informacion suministrada por las pruebas, es de suma importancia resaltar
la relevancia de la variable <span class="math inline">\(duration\)</span> (primordialmente), la cual muestra diferencias
significativas entre ambos grupos y confirma lo proyectado en el EDA, catalogandola como una variable fuerte en relacion con la variable objetivo. Seguido a la variable <span class="math inline">\(duration\)</span>, las variables <span class="math inline">\(pdays\)</span>, <span class="math inline">\(campaign\)</span> y <span class="math inline">\(balance\)</span> señalan diferencias significativas entre los grupos; y por ultimo, la variable <span class="math inline">\(age\)</span> definitivamente no es de mayor impacto y por tanto no es necesario tenerla en cuenta para predecir la variable objetivo <span class="math inline">\(y\)</span>.</p>
</div>
<div id="tecnicas-inferenciales-entre-las-variables-categoricas-y-la-variable-objetivo" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Tecnicas inferenciales entre las variables categoricas y la variable objetivo<a href="bivariado-con-variables-categoricas.html#tecnicas-inferenciales-entre-las-variables-categoricas-y-la-variable-objetivo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A continuación, se presentan los resultados del análisis de asociación entre diferentes variables categóricas del conjunto de datos y la variable objetivo Y, que representa la respuesta del cliente a la campaña de depósito a plazo.
Para este propósito, se utilizaron tablas de contingencia que permiten observar la distribución conjunta de las categorías, junto con la prueba de Chi-cuadrado de independencia, la cual evalúa si existe una relación estadísticamente significativa entre cada variable independiente y la respuesta del cliente.
De esta manera, se busca determinar qué características de los clientes están asociadas a una mayor o menor probabilidad de aceptar el producto ofrecido por la entidad bancaria.</p>
<p><strong>TABLA JOB vs Y</strong></p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="bivariado-con-variables-categoricas.html#cb64-1" tabindex="-1"></a>bd <span class="ot">&lt;-</span> data</span>
<span id="cb64-2"><a href="bivariado-con-variables-categoricas.html#cb64-2" tabindex="-1"></a>observados <span class="ot">&lt;-</span> <span class="fu">table</span>(bd<span class="sc">$</span>job, bd<span class="sc">$</span>y)</span>
<span id="cb64-3"><a href="bivariado-con-variables-categoricas.html#cb64-3" tabindex="-1"></a>observados</span></code></pre></div>
<pre><code>##                
##                  no yes
##   admin.        420  58
##   blue-collar   877  69
##   entrepreneur  153  15
##   housemaid      98  14
##   management    838 131
##   retired       176  54
##   self-employed 163  20
##   services      379  38
##   student        65  19
##   technician    685  83
##   unemployed    115  13
##   unknown        31   7</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="bivariado-con-variables-categoricas.html#cb66-1" tabindex="-1"></a>filas_totales <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(observados)</span>
<span id="cb66-2"><a href="bivariado-con-variables-categoricas.html#cb66-2" tabindex="-1"></a>col_totales <span class="ot">&lt;-</span> <span class="fu">colSums</span>(observados)</span>
<span id="cb66-3"><a href="bivariado-con-variables-categoricas.html#cb66-3" tabindex="-1"></a>total_general <span class="ot">&lt;-</span> <span class="fu">sum</span>(observados)</span>
<span id="cb66-4"><a href="bivariado-con-variables-categoricas.html#cb66-4" tabindex="-1"></a></span>
<span id="cb66-5"><a href="bivariado-con-variables-categoricas.html#cb66-5" tabindex="-1"></a>esperados <span class="ot">&lt;-</span> <span class="fu">outer</span>(filas_totales, col_totales, <span class="at">FUN =</span> <span class="cf">function</span>(f,c) f<span class="sc">*</span>c <span class="sc">/</span> total_general)</span>
<span id="cb66-6"><a href="bivariado-con-variables-categoricas.html#cb66-6" tabindex="-1"></a><span class="fu">dimnames</span>(esperados) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(observados)</span>
<span id="cb66-7"><a href="bivariado-con-variables-categoricas.html#cb66-7" tabindex="-1"></a>esperados</span></code></pre></div>
<pre><code>##                
##                        no        yes
##   admin.        422.91528  55.084716
##   blue-collar   836.98297 109.017032
##   entrepreneur  148.63968  19.360319
##   housemaid      99.09312  12.906879
##   management    857.33245 111.667551
##   retired       203.49480  26.505198
##   self-employed 161.91108  21.088918
##   services      368.94492  48.055076
##   student        74.31984   9.680159
##   technician    679.49569  88.504313
##   unemployed    113.24928  14.750719
##   unknown        33.62088   4.379120</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="bivariado-con-variables-categoricas.html#cb68-1" tabindex="-1"></a><span class="co">#AQUI AGRUPAMOS unemployed/con unknown para que nos queden los esperados mayores a 5</span></span>
<span id="cb68-2"><a href="bivariado-con-variables-categoricas.html#cb68-2" tabindex="-1"></a>agru <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb68-3"><a href="bivariado-con-variables-categoricas.html#cb68-3" tabindex="-1"></a>  <span class="st">&quot;unemployed/unknown&quot;</span> <span class="ot">=</span> <span class="fu">colSums</span>(observados[<span class="fu">c</span>(<span class="st">&quot;unemployed&quot;</span>, <span class="st">&quot;unknown&quot;</span>), ]),</span>
<span id="cb68-4"><a href="bivariado-con-variables-categoricas.html#cb68-4" tabindex="-1"></a>  observados[<span class="sc">!</span><span class="fu">rownames</span>(observados) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;unemployed&quot;</span>, <span class="st">&quot;unknown&quot;</span>), ]</span>
<span id="cb68-5"><a href="bivariado-con-variables-categoricas.html#cb68-5" tabindex="-1"></a>)</span>
<span id="cb68-6"><a href="bivariado-con-variables-categoricas.html#cb68-6" tabindex="-1"></a>agru</span></code></pre></div>
<pre><code>##                     no yes
## unemployed/unknown 146  20
## admin.             420  58
## blue-collar        877  69
## entrepreneur       153  15
## housemaid           98  14
## management         838 131
## retired            176  54
## self-employed      163  20
## services           379  38
## student             65  19
## technician         685  83</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="bivariado-con-variables-categoricas.html#cb70-1" tabindex="-1"></a>filas <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(agru)</span>
<span id="cb70-2"><a href="bivariado-con-variables-categoricas.html#cb70-2" tabindex="-1"></a>columnas <span class="ot">&lt;-</span> <span class="fu">colSums</span>(agru)</span>
<span id="cb70-3"><a href="bivariado-con-variables-categoricas.html#cb70-3" tabindex="-1"></a>totalg <span class="ot">&lt;-</span> <span class="fu">sum</span>(agru)</span>
<span id="cb70-4"><a href="bivariado-con-variables-categoricas.html#cb70-4" tabindex="-1"></a></span>
<span id="cb70-5"><a href="bivariado-con-variables-categoricas.html#cb70-5" tabindex="-1"></a>esperados_n <span class="ot">&lt;-</span> <span class="fu">outer</span>(filas, columnas, <span class="at">FUN =</span> <span class="cf">function</span>(f,c) f<span class="sc">*</span>c <span class="sc">/</span> totalg)</span>
<span id="cb70-6"><a href="bivariado-con-variables-categoricas.html#cb70-6" tabindex="-1"></a><span class="fu">dimnames</span>(esperados_n) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(agru)</span>
<span id="cb70-7"><a href="bivariado-con-variables-categoricas.html#cb70-7" tabindex="-1"></a>esperados_n</span></code></pre></div>
<pre><code>##                           no        yes
## unemployed/unknown 146.87016  19.129839
## admin.             422.91528  55.084716
## blue-collar        836.98297 109.017032
## entrepreneur       148.63968  19.360319
## housemaid           99.09312  12.906879
## management         857.33245 111.667551
## retired            203.49480  26.505198
## self-employed      161.91108  21.088918
## services           368.94492  48.055076
## student             74.31984   9.680159
## technician         679.49569  88.504313</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="bivariado-con-variables-categoricas.html#cb72-1" tabindex="-1"></a>chi_cuadrado_n <span class="ot">&lt;-</span> <span class="fu">sum</span>((agru <span class="sc">-</span> esperados_n)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> esperados_n)</span>
<span id="cb72-2"><a href="bivariado-con-variables-categoricas.html#cb72-2" tabindex="-1"></a>chi_cuadrado_n</span></code></pre></div>
<pre><code>## [1] 67.02528</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="bivariado-con-variables-categoricas.html#cb74-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> (<span class="fu">nrow</span>(agru)<span class="sc">-</span><span class="dv">1</span>) <span class="sc">*</span> (<span class="fu">ncol</span>(agru)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb74-2"><a href="bivariado-con-variables-categoricas.html#cb74-2" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="bivariado-con-variables-categoricas.html#cb76-1" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb76-2"><a href="bivariado-con-variables-categoricas.html#cb76-2" tabindex="-1"></a>valor_critico <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span> <span class="sc">-</span> alpha, df)</span>
<span id="cb76-3"><a href="bivariado-con-variables-categoricas.html#cb76-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 18.30704</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="bivariado-con-variables-categoricas.html#cb78-1" tabindex="-1"></a>rechaza_H0 <span class="ot">&lt;-</span> chi_cuadrado_n <span class="sc">&gt;</span> valor_critico</span>
<span id="cb78-2"><a href="bivariado-con-variables-categoricas.html#cb78-2" tabindex="-1"></a>rechaza_H0</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="bivariado-con-variables-categoricas.html#cb80-1" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(chi_cuadrado_n, df, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb80-2"><a href="bivariado-con-variables-categoricas.html#cb80-2" tabindex="-1"></a>p_value</span></code></pre></div>
<pre><code>## [1] 1.65812e-10</code></pre>
<p>Se rechaza la hipótesis nula, por lo tanto, existe una relación significativa entre el tipo de empleo del cliente y su respuesta a la campaña de depósito a plazo. Esto indica que el tipo de trabajo influye en la probabilidad de que el cliente acepte o no el producto ofrecido.</p>
<p><strong>TABLA MARITAL vs Y</strong></p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="bivariado-con-variables-categoricas.html#cb82-1" tabindex="-1"></a>observados <span class="ot">&lt;-</span> <span class="fu">table</span>(bd<span class="sc">$</span>marital, bd<span class="sc">$</span>y)</span>
<span id="cb82-2"><a href="bivariado-con-variables-categoricas.html#cb82-2" tabindex="-1"></a>observados</span></code></pre></div>
<pre><code>##           
##              no  yes
##   divorced  451   77
##   married  2520  277
##   single   1029  167</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="bivariado-con-variables-categoricas.html#cb84-1" tabindex="-1"></a>filas_totales <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(observados)</span>
<span id="cb84-2"><a href="bivariado-con-variables-categoricas.html#cb84-2" tabindex="-1"></a>col_totales <span class="ot">&lt;-</span> <span class="fu">colSums</span>(observados)</span>
<span id="cb84-3"><a href="bivariado-con-variables-categoricas.html#cb84-3" tabindex="-1"></a>total_general <span class="ot">&lt;-</span> <span class="fu">sum</span>(observados)</span>
<span id="cb84-4"><a href="bivariado-con-variables-categoricas.html#cb84-4" tabindex="-1"></a></span>
<span id="cb84-5"><a href="bivariado-con-variables-categoricas.html#cb84-5" tabindex="-1"></a>esperados <span class="ot">&lt;-</span> <span class="fu">outer</span>(filas_totales, col_totales, <span class="at">FUN =</span> <span class="cf">function</span>(f,c) f<span class="sc">*</span>c <span class="sc">/</span> total_general)</span>
<span id="cb84-6"><a href="bivariado-con-variables-categoricas.html#cb84-6" tabindex="-1"></a><span class="fu">dimnames</span>(esperados) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(observados)</span>
<span id="cb84-7"><a href="bivariado-con-variables-categoricas.html#cb84-7" tabindex="-1"></a>esperados</span></code></pre></div>
<pre><code>##           
##                   no       yes
##   divorced  467.1533  60.84672
##   married  2474.6737 322.32626
##   single   1058.1730 137.82703</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="bivariado-con-variables-categoricas.html#cb86-1" tabindex="-1"></a>chi_cuadrado <span class="ot">&lt;-</span> <span class="fu">sum</span>((observados <span class="sc">-</span> esperados)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> esperados)</span>
<span id="cb86-2"><a href="bivariado-con-variables-categoricas.html#cb86-2" tabindex="-1"></a>chi_cuadrado</span></code></pre></div>
<pre><code>## [1] 19.03006</code></pre>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="bivariado-con-variables-categoricas.html#cb88-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> (<span class="fu">nrow</span>(observados)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>(<span class="fu">ncol</span>(observados)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb88-2"><a href="bivariado-con-variables-categoricas.html#cb88-2" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="bivariado-con-variables-categoricas.html#cb90-1" tabindex="-1"></a>alfa <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb90-2"><a href="bivariado-con-variables-categoricas.html#cb90-2" tabindex="-1"></a>valor_critico <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alfa,df)</span>
<span id="cb90-3"><a href="bivariado-con-variables-categoricas.html#cb90-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 5.991465</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="bivariado-con-variables-categoricas.html#cb92-1" tabindex="-1"></a>rechaza_H0 <span class="ot">&lt;-</span> chi_cuadrado <span class="sc">&gt;</span> valor_critico</span>
<span id="cb92-2"><a href="bivariado-con-variables-categoricas.html#cb92-2" tabindex="-1"></a>rechaza_H0</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="bivariado-con-variables-categoricas.html#cb94-1" tabindex="-1"></a><span class="cf">if</span> (rechaza_H0) {</span>
<span id="cb94-2"><a href="bivariado-con-variables-categoricas.html#cb94-2" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</span></span>
<span id="cb94-3"><a href="bivariado-con-variables-categoricas.html#cb94-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb94-4"><a href="bivariado-con-variables-categoricas.html#cb94-4" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es menor que el valor crítico, aceptamos H0.&quot;</span></span>
<span id="cb94-5"><a href="bivariado-con-variables-categoricas.html#cb94-5" tabindex="-1"></a>}</span>
<span id="cb94-6"><a href="bivariado-con-variables-categoricas.html#cb94-6" tabindex="-1"></a>conclusion</span></code></pre></div>
<pre><code>## [1] &quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</code></pre>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="bivariado-con-variables-categoricas.html#cb96-1" tabindex="-1"></a>valor_p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(chi_cuadrado,df,<span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb96-2"><a href="bivariado-con-variables-categoricas.html#cb96-2" tabindex="-1"></a>valor_p</span></code></pre></div>
<pre><code>## [1] 7.373535e-05</code></pre>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="bivariado-con-variables-categoricas.html#cb98-1" tabindex="-1"></a><span class="fu">chisq.test</span>(observados)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  observados
## X-squared = 19.03, df = 2, p-value = 7.374e-05</code></pre>
<p>Se rechaza la hipótesis nula, por lo que hay evidencia estadística de una relación entre el estado civil del cliente y su respuesta a la campaña. Esto sugiere que el estado civil podría estar asociado a distintos niveles de interés o disponibilidad para contratar el depósito.</p>
<p><strong>TABLA EDUCATION vs Y</strong></p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="bivariado-con-variables-categoricas.html#cb100-1" tabindex="-1"></a>observados <span class="ot">&lt;-</span> <span class="fu">table</span>(bd<span class="sc">$</span>education, bd<span class="sc">$</span>y)</span>
<span id="cb100-2"><a href="bivariado-con-variables-categoricas.html#cb100-2" tabindex="-1"></a>observados</span></code></pre></div>
<pre><code>##            
##               no  yes
##   primary    614   64
##   secondary 2061  245
##   tertiary  1157  193
##   unknown    168   19</code></pre>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="bivariado-con-variables-categoricas.html#cb102-1" tabindex="-1"></a>filas_totales <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(observados)</span>
<span id="cb102-2"><a href="bivariado-con-variables-categoricas.html#cb102-2" tabindex="-1"></a>col_totales <span class="ot">&lt;-</span> <span class="fu">colSums</span>(observados)</span>
<span id="cb102-3"><a href="bivariado-con-variables-categoricas.html#cb102-3" tabindex="-1"></a>total_general <span class="ot">&lt;-</span> <span class="fu">sum</span>(observados)</span>
<span id="cb102-4"><a href="bivariado-con-variables-categoricas.html#cb102-4" tabindex="-1"></a></span>
<span id="cb102-5"><a href="bivariado-con-variables-categoricas.html#cb102-5" tabindex="-1"></a>esperados <span class="ot">&lt;-</span> <span class="fu">outer</span>(filas_totales, col_totales, <span class="at">FUN =</span> <span class="cf">function</span>(f,c) f<span class="sc">*</span>c <span class="sc">/</span> total_general)</span>
<span id="cb102-6"><a href="bivariado-con-variables-categoricas.html#cb102-6" tabindex="-1"></a><span class="fu">dimnames</span>(esperados) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(observados)</span>
<span id="cb102-7"><a href="bivariado-con-variables-categoricas.html#cb102-7" tabindex="-1"></a>esperados</span></code></pre></div>
<pre><code>##            
##                    no       yes
##   primary    599.8673  78.13271
##   secondary 2040.2566 265.74342
##   tertiary  1194.4260 155.57399
##   unknown    165.4501  21.54988</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="bivariado-con-variables-categoricas.html#cb104-1" tabindex="-1"></a>chi_cuadrado <span class="ot">&lt;-</span> <span class="fu">sum</span>((observados <span class="sc">-</span> esperados)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> esperados)</span>
<span id="cb104-2"><a href="bivariado-con-variables-categoricas.html#cb104-2" tabindex="-1"></a>chi_cuadrado</span></code></pre></div>
<pre><code>## [1] 15.23658</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="bivariado-con-variables-categoricas.html#cb106-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> (<span class="fu">nrow</span>(observados)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>(<span class="fu">ncol</span>(observados)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb106-2"><a href="bivariado-con-variables-categoricas.html#cb106-2" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="bivariado-con-variables-categoricas.html#cb108-1" tabindex="-1"></a>alfa <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb108-2"><a href="bivariado-con-variables-categoricas.html#cb108-2" tabindex="-1"></a>valor_critico <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alfa,df)</span>
<span id="cb108-3"><a href="bivariado-con-variables-categoricas.html#cb108-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 7.814728</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="bivariado-con-variables-categoricas.html#cb110-1" tabindex="-1"></a>rechaza_H0 <span class="ot">&lt;-</span> chi_cuadrado <span class="sc">&gt;</span> valor_critico</span>
<span id="cb110-2"><a href="bivariado-con-variables-categoricas.html#cb110-2" tabindex="-1"></a>rechaza_H0</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="bivariado-con-variables-categoricas.html#cb112-1" tabindex="-1"></a><span class="cf">if</span> (rechaza_H0) {</span>
<span id="cb112-2"><a href="bivariado-con-variables-categoricas.html#cb112-2" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</span></span>
<span id="cb112-3"><a href="bivariado-con-variables-categoricas.html#cb112-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb112-4"><a href="bivariado-con-variables-categoricas.html#cb112-4" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es menor que el valor crítico, aceptamos H0.&quot;</span></span>
<span id="cb112-5"><a href="bivariado-con-variables-categoricas.html#cb112-5" tabindex="-1"></a>}</span>
<span id="cb112-6"><a href="bivariado-con-variables-categoricas.html#cb112-6" tabindex="-1"></a>conclusion</span></code></pre></div>
<pre><code>## [1] &quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</code></pre>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="bivariado-con-variables-categoricas.html#cb114-1" tabindex="-1"></a>valor_p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(chi_cuadrado,df,<span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb114-2"><a href="bivariado-con-variables-categoricas.html#cb114-2" tabindex="-1"></a>valor_p</span></code></pre></div>
<pre><code>## [1] 0.00162524</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="bivariado-con-variables-categoricas.html#cb116-1" tabindex="-1"></a><span class="fu">chisq.test</span>(observados)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  observados
## X-squared = 15.237, df = 3, p-value = 0.001625</code></pre>
<p>Dado que se rechaza la hipótesis nula, se concluye que existe una asociación significativa entre el nivel educativo del cliente y su decisión de aceptar el depósito a plazo. Esto puede reflejar diferencias en conocimiento financiero o en confianza hacia los productos bancarios según la formación académica.</p>
<p><strong>TABLA DEFAULT vs Y</strong></p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="bivariado-con-variables-categoricas.html#cb118-1" tabindex="-1"></a>observados <span class="ot">&lt;-</span> <span class="fu">table</span>(bd<span class="sc">$</span>default, bd<span class="sc">$</span>y)</span>
<span id="cb118-2"><a href="bivariado-con-variables-categoricas.html#cb118-2" tabindex="-1"></a>observados</span></code></pre></div>
<pre><code>##      
##         no  yes
##   no  3933  512
##   yes   67    9</code></pre>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="bivariado-con-variables-categoricas.html#cb120-1" tabindex="-1"></a>filas_totales <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(observados)</span>
<span id="cb120-2"><a href="bivariado-con-variables-categoricas.html#cb120-2" tabindex="-1"></a>col_totales <span class="ot">&lt;-</span> <span class="fu">colSums</span>(observados)</span>
<span id="cb120-3"><a href="bivariado-con-variables-categoricas.html#cb120-3" tabindex="-1"></a>total_general <span class="ot">&lt;-</span> <span class="fu">sum</span>(observados)</span>
<span id="cb120-4"><a href="bivariado-con-variables-categoricas.html#cb120-4" tabindex="-1"></a></span>
<span id="cb120-5"><a href="bivariado-con-variables-categoricas.html#cb120-5" tabindex="-1"></a>esperados <span class="ot">&lt;-</span> <span class="fu">outer</span>(filas_totales, col_totales, <span class="at">FUN =</span> <span class="cf">function</span>(f,c) f<span class="sc">*</span>c <span class="sc">/</span> total_general)</span>
<span id="cb120-6"><a href="bivariado-con-variables-categoricas.html#cb120-6" tabindex="-1"></a><span class="fu">dimnames</span>(esperados) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(observados)</span>
<span id="cb120-7"><a href="bivariado-con-variables-categoricas.html#cb120-7" tabindex="-1"></a>esperados</span></code></pre></div>
<pre><code>##      
##               no        yes
##   no  3932.75824 512.241761
##   yes   67.24176   8.758239</code></pre>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="bivariado-con-variables-categoricas.html#cb122-1" tabindex="-1"></a>chi_cuadrado <span class="ot">&lt;-</span> <span class="fu">sum</span>((observados <span class="sc">-</span> esperados)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> esperados)</span>
<span id="cb122-2"><a href="bivariado-con-variables-categoricas.html#cb122-2" tabindex="-1"></a>chi_cuadrado</span></code></pre></div>
<pre><code>## [1] 0.007671703</code></pre>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="bivariado-con-variables-categoricas.html#cb124-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> (<span class="fu">nrow</span>(observados)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>(<span class="fu">ncol</span>(observados)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb124-2"><a href="bivariado-con-variables-categoricas.html#cb124-2" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="bivariado-con-variables-categoricas.html#cb126-1" tabindex="-1"></a>alfa <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb126-2"><a href="bivariado-con-variables-categoricas.html#cb126-2" tabindex="-1"></a>valor_critico <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alfa,df)</span>
<span id="cb126-3"><a href="bivariado-con-variables-categoricas.html#cb126-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 3.841459</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="bivariado-con-variables-categoricas.html#cb128-1" tabindex="-1"></a>rechaza_H0 <span class="ot">&lt;-</span> chi_cuadrado <span class="sc">&gt;</span> valor_critico</span>
<span id="cb128-2"><a href="bivariado-con-variables-categoricas.html#cb128-2" tabindex="-1"></a>rechaza_H0</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="bivariado-con-variables-categoricas.html#cb130-1" tabindex="-1"></a><span class="cf">if</span> (rechaza_H0) {</span>
<span id="cb130-2"><a href="bivariado-con-variables-categoricas.html#cb130-2" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</span></span>
<span id="cb130-3"><a href="bivariado-con-variables-categoricas.html#cb130-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb130-4"><a href="bivariado-con-variables-categoricas.html#cb130-4" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es menor que el valor crítico, aceptamos H0.&quot;</span></span>
<span id="cb130-5"><a href="bivariado-con-variables-categoricas.html#cb130-5" tabindex="-1"></a>}</span>
<span id="cb130-6"><a href="bivariado-con-variables-categoricas.html#cb130-6" tabindex="-1"></a>conclusion</span></code></pre></div>
<pre><code>## [1] &quot;Como chi_cuadrado es menor que el valor crítico, aceptamos H0.&quot;</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="bivariado-con-variables-categoricas.html#cb132-1" tabindex="-1"></a>valor_p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(chi_cuadrado,df,<span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb132-2"><a href="bivariado-con-variables-categoricas.html#cb132-2" tabindex="-1"></a>valor_p</span></code></pre></div>
<pre><code>## [1] 0.9302039</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="bivariado-con-variables-categoricas.html#cb134-1" tabindex="-1"></a><span class="fu">chisq.test</span>(observados)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  observados
## X-squared = 1.1844e-27, df = 1, p-value = 1</code></pre>
<p>No se rechaza la hipótesis nula, lo que indica que no existe una relación estadísticamente significativa entre tener deudas en incumplimiento y la respuesta del cliente. En este caso, el hecho de tener o no un crédito en mora no influye de manera importante en la decisión de aceptar el producto ofrecido.</p>
<p><strong>TABLA HOUSING vs Y</strong></p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="bivariado-con-variables-categoricas.html#cb136-1" tabindex="-1"></a>observados <span class="ot">&lt;-</span> <span class="fu">table</span>(bd<span class="sc">$</span>housing, bd<span class="sc">$</span>y)</span>
<span id="cb136-2"><a href="bivariado-con-variables-categoricas.html#cb136-2" tabindex="-1"></a>observados</span></code></pre></div>
<pre><code>##      
##         no  yes
##   no  1661  301
##   yes 2339  220</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="bivariado-con-variables-categoricas.html#cb138-1" tabindex="-1"></a>filas_totales <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(observados)</span>
<span id="cb138-2"><a href="bivariado-con-variables-categoricas.html#cb138-2" tabindex="-1"></a>col_totales <span class="ot">&lt;-</span> <span class="fu">colSums</span>(observados)</span>
<span id="cb138-3"><a href="bivariado-con-variables-categoricas.html#cb138-3" tabindex="-1"></a>total_general <span class="ot">&lt;-</span> <span class="fu">sum</span>(observados)</span>
<span id="cb138-4"><a href="bivariado-con-variables-categoricas.html#cb138-4" tabindex="-1"></a></span>
<span id="cb138-5"><a href="bivariado-con-variables-categoricas.html#cb138-5" tabindex="-1"></a>esperados <span class="ot">&lt;-</span> <span class="fu">outer</span>(filas_totales, col_totales, <span class="at">FUN =</span> <span class="cf">function</span>(f,c) f<span class="sc">*</span>c <span class="sc">/</span> total_general)</span>
<span id="cb138-6"><a href="bivariado-con-variables-categoricas.html#cb138-6" tabindex="-1"></a><span class="fu">dimnames</span>(esperados) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(observados)</span>
<span id="cb138-7"><a href="bivariado-con-variables-categoricas.html#cb138-7" tabindex="-1"></a>esperados</span></code></pre></div>
<pre><code>##      
##             no      yes
##   no  1735.899 226.1009
##   yes 2264.101 294.8991</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="bivariado-con-variables-categoricas.html#cb140-1" tabindex="-1"></a>chi_cuadrado <span class="ot">&lt;-</span> <span class="fu">sum</span>((observados <span class="sc">-</span> esperados)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> esperados)</span>
<span id="cb140-2"><a href="bivariado-con-variables-categoricas.html#cb140-2" tabindex="-1"></a>chi_cuadrado</span></code></pre></div>
<pre><code>## [1] 49.5439</code></pre>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="bivariado-con-variables-categoricas.html#cb142-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> (<span class="fu">nrow</span>(observados)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>(<span class="fu">ncol</span>(observados)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb142-2"><a href="bivariado-con-variables-categoricas.html#cb142-2" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="bivariado-con-variables-categoricas.html#cb144-1" tabindex="-1"></a>alfa <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb144-2"><a href="bivariado-con-variables-categoricas.html#cb144-2" tabindex="-1"></a>valor_critico <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alfa,df)</span>
<span id="cb144-3"><a href="bivariado-con-variables-categoricas.html#cb144-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 3.841459</code></pre>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="bivariado-con-variables-categoricas.html#cb146-1" tabindex="-1"></a>rechaza_H0 <span class="ot">&lt;-</span> chi_cuadrado <span class="sc">&gt;</span> valor_critico</span>
<span id="cb146-2"><a href="bivariado-con-variables-categoricas.html#cb146-2" tabindex="-1"></a>rechaza_H0</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="bivariado-con-variables-categoricas.html#cb148-1" tabindex="-1"></a><span class="cf">if</span> (rechaza_H0) {</span>
<span id="cb148-2"><a href="bivariado-con-variables-categoricas.html#cb148-2" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</span></span>
<span id="cb148-3"><a href="bivariado-con-variables-categoricas.html#cb148-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb148-4"><a href="bivariado-con-variables-categoricas.html#cb148-4" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es menor que el valor crítico, aceptamos H0.&quot;</span></span>
<span id="cb148-5"><a href="bivariado-con-variables-categoricas.html#cb148-5" tabindex="-1"></a>}</span>
<span id="cb148-6"><a href="bivariado-con-variables-categoricas.html#cb148-6" tabindex="-1"></a>conclusion</span></code></pre></div>
<pre><code>## [1] &quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="bivariado-con-variables-categoricas.html#cb150-1" tabindex="-1"></a>valor_p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(chi_cuadrado,df,<span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb150-2"><a href="bivariado-con-variables-categoricas.html#cb150-2" tabindex="-1"></a>valor_p</span></code></pre></div>
<pre><code>## [1] 1.939825e-12</code></pre>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="bivariado-con-variables-categoricas.html#cb152-1" tabindex="-1"></a><span class="fu">chisq.test</span>(observados)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  observados
## X-squared = 48.885, df = 1, p-value = 2.715e-12</code></pre>
<p>Existe evidencia estadísticamente significativa (p &lt; 0.05) para rechazar la hipótesis nula, por lo tanto, el tener o no un crédito hipotecario está asociado con el interés en adquirir un depósito a plazo fijo.
Es decir, el comportamiento de los clientes frente a la oferta de depósito varía según si poseen o no una hipoteca.</p>
<p><strong>TABLA LOAN vs Y</strong></p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="bivariado-con-variables-categoricas.html#cb154-1" tabindex="-1"></a>observados <span class="ot">&lt;-</span> <span class="fu">table</span>(bd<span class="sc">$</span>loan, bd<span class="sc">$</span>y)</span>
<span id="cb154-2"><a href="bivariado-con-variables-categoricas.html#cb154-2" tabindex="-1"></a>observados</span></code></pre></div>
<pre><code>##      
##         no  yes
##   no  3352  478
##   yes  648   43</code></pre>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="bivariado-con-variables-categoricas.html#cb156-1" tabindex="-1"></a>filas_totales <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(observados)</span>
<span id="cb156-2"><a href="bivariado-con-variables-categoricas.html#cb156-2" tabindex="-1"></a>col_totales <span class="ot">&lt;-</span> <span class="fu">colSums</span>(observados)</span>
<span id="cb156-3"><a href="bivariado-con-variables-categoricas.html#cb156-3" tabindex="-1"></a>total_general <span class="ot">&lt;-</span> <span class="fu">sum</span>(observados)</span>
<span id="cb156-4"><a href="bivariado-con-variables-categoricas.html#cb156-4" tabindex="-1"></a></span>
<span id="cb156-5"><a href="bivariado-con-variables-categoricas.html#cb156-5" tabindex="-1"></a>esperados <span class="ot">&lt;-</span> <span class="fu">outer</span>(filas_totales, col_totales, <span class="at">FUN =</span> <span class="cf">function</span>(f,c) f<span class="sc">*</span>c <span class="sc">/</span> total_general)</span>
<span id="cb156-6"><a href="bivariado-con-variables-categoricas.html#cb156-6" tabindex="-1"></a><span class="fu">dimnames</span>(esperados) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(observados)</span>
<span id="cb156-7"><a href="bivariado-con-variables-categoricas.html#cb156-7" tabindex="-1"></a>esperados</span></code></pre></div>
<pre><code>##      
##              no       yes
##   no  3388.6308 441.36917
##   yes  611.3692  79.63083</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="bivariado-con-variables-categoricas.html#cb158-1" tabindex="-1"></a>chi_cuadrado <span class="ot">&lt;-</span> <span class="fu">sum</span>((observados <span class="sc">-</span> esperados)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> esperados)</span>
<span id="cb158-2"><a href="bivariado-con-variables-categoricas.html#cb158-2" tabindex="-1"></a>chi_cuadrado</span></code></pre></div>
<pre><code>## [1] 22.48136</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="bivariado-con-variables-categoricas.html#cb160-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> (<span class="fu">nrow</span>(observados)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>(<span class="fu">ncol</span>(observados)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb160-2"><a href="bivariado-con-variables-categoricas.html#cb160-2" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="bivariado-con-variables-categoricas.html#cb162-1" tabindex="-1"></a>alfa <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb162-2"><a href="bivariado-con-variables-categoricas.html#cb162-2" tabindex="-1"></a>valor_critico <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alfa,df)</span>
<span id="cb162-3"><a href="bivariado-con-variables-categoricas.html#cb162-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 3.841459</code></pre>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="bivariado-con-variables-categoricas.html#cb164-1" tabindex="-1"></a>rechaza_H0 <span class="ot">&lt;-</span> chi_cuadrado <span class="sc">&gt;</span> valor_critico</span>
<span id="cb164-2"><a href="bivariado-con-variables-categoricas.html#cb164-2" tabindex="-1"></a>rechaza_H0</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="bivariado-con-variables-categoricas.html#cb166-1" tabindex="-1"></a><span class="cf">if</span> (rechaza_H0) {</span>
<span id="cb166-2"><a href="bivariado-con-variables-categoricas.html#cb166-2" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</span></span>
<span id="cb166-3"><a href="bivariado-con-variables-categoricas.html#cb166-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb166-4"><a href="bivariado-con-variables-categoricas.html#cb166-4" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es menor que el valor crítico, aceptamos H0.&quot;</span></span>
<span id="cb166-5"><a href="bivariado-con-variables-categoricas.html#cb166-5" tabindex="-1"></a>}</span>
<span id="cb166-6"><a href="bivariado-con-variables-categoricas.html#cb166-6" tabindex="-1"></a>conclusion</span></code></pre></div>
<pre><code>## [1] &quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="bivariado-con-variables-categoricas.html#cb168-1" tabindex="-1"></a>valor_p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(chi_cuadrado,df,<span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb168-2"><a href="bivariado-con-variables-categoricas.html#cb168-2" tabindex="-1"></a>valor_p</span></code></pre></div>
<pre><code>## [1] 2.121926e-06</code></pre>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="bivariado-con-variables-categoricas.html#cb170-1" tabindex="-1"></a><span class="fu">chisq.test</span>(observados)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  observados
## X-squared = 21.872, df = 1, p-value = 2.915e-06</code></pre>
<p>Se rechaza la hipótesis nula, indicando que tener un préstamo personal está asociado con el interés en un depósito a plazo fijo.
En otras palabras, el interés por el depósito no es independiente del hecho de tener un préstamo, lo cual puede reflejar diferencias en el perfil financiero o capacidad de ahorro de los clientes.</p>
<p><strong>TABLA CONTACT vs Y</strong></p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="bivariado-con-variables-categoricas.html#cb172-1" tabindex="-1"></a>observados <span class="ot">&lt;-</span> <span class="fu">table</span>(bd<span class="sc">$</span>contact, bd<span class="sc">$</span>y)</span>
<span id="cb172-2"><a href="bivariado-con-variables-categoricas.html#cb172-2" tabindex="-1"></a>observados</span></code></pre></div>
<pre><code>##            
##               no  yes
##   cellular  2480  416
##   telephone  257   44
##   unknown   1263   61</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="bivariado-con-variables-categoricas.html#cb174-1" tabindex="-1"></a>filas_totales <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(observados)</span>
<span id="cb174-2"><a href="bivariado-con-variables-categoricas.html#cb174-2" tabindex="-1"></a>col_totales <span class="ot">&lt;-</span> <span class="fu">colSums</span>(observados)</span>
<span id="cb174-3"><a href="bivariado-con-variables-categoricas.html#cb174-3" tabindex="-1"></a>total_general <span class="ot">&lt;-</span> <span class="fu">sum</span>(observados)</span>
<span id="cb174-4"><a href="bivariado-con-variables-categoricas.html#cb174-4" tabindex="-1"></a></span>
<span id="cb174-5"><a href="bivariado-con-variables-categoricas.html#cb174-5" tabindex="-1"></a>esperados <span class="ot">&lt;-</span> <span class="fu">outer</span>(filas_totales, col_totales, <span class="at">FUN =</span> <span class="cf">function</span>(f,c) f<span class="sc">*</span>c <span class="sc">/</span> total_general)</span>
<span id="cb174-6"><a href="bivariado-con-variables-categoricas.html#cb174-6" tabindex="-1"></a><span class="fu">dimnames</span>(esperados) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(observados)</span>
<span id="cb174-7"><a href="bivariado-con-variables-categoricas.html#cb174-7" tabindex="-1"></a>esperados</span></code></pre></div>
<pre><code>##            
##                    no       yes
##   cellular  2562.2650 333.73501
##   telephone  266.3128  34.68724
##   unknown   1171.4223 152.57775</code></pre>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="bivariado-con-variables-categoricas.html#cb176-1" tabindex="-1"></a>chi_cuadrado <span class="ot">&lt;-</span> <span class="fu">sum</span>((observados <span class="sc">-</span> esperados)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> esperados)</span>
<span id="cb176-2"><a href="bivariado-con-variables-categoricas.html#cb176-2" tabindex="-1"></a>chi_cuadrado</span></code></pre></div>
<pre><code>## [1] 87.86986</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="bivariado-con-variables-categoricas.html#cb178-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> (<span class="fu">nrow</span>(observados)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>(<span class="fu">ncol</span>(observados)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb178-2"><a href="bivariado-con-variables-categoricas.html#cb178-2" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="bivariado-con-variables-categoricas.html#cb180-1" tabindex="-1"></a>alfa <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb180-2"><a href="bivariado-con-variables-categoricas.html#cb180-2" tabindex="-1"></a>valor_critico <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alfa,df)</span>
<span id="cb180-3"><a href="bivariado-con-variables-categoricas.html#cb180-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 5.991465</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="bivariado-con-variables-categoricas.html#cb182-1" tabindex="-1"></a>rechaza_H0 <span class="ot">&lt;-</span> chi_cuadrado <span class="sc">&gt;</span> valor_critico</span>
<span id="cb182-2"><a href="bivariado-con-variables-categoricas.html#cb182-2" tabindex="-1"></a>rechaza_H0</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="bivariado-con-variables-categoricas.html#cb184-1" tabindex="-1"></a><span class="cf">if</span> (rechaza_H0) {</span>
<span id="cb184-2"><a href="bivariado-con-variables-categoricas.html#cb184-2" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</span></span>
<span id="cb184-3"><a href="bivariado-con-variables-categoricas.html#cb184-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb184-4"><a href="bivariado-con-variables-categoricas.html#cb184-4" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es menor que el valor crítico, aceptamos H0.&quot;</span></span>
<span id="cb184-5"><a href="bivariado-con-variables-categoricas.html#cb184-5" tabindex="-1"></a>}</span>
<span id="cb184-6"><a href="bivariado-con-variables-categoricas.html#cb184-6" tabindex="-1"></a>conclusion</span></code></pre></div>
<pre><code>## [1] &quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</code></pre>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="bivariado-con-variables-categoricas.html#cb186-1" tabindex="-1"></a>valor_p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(chi_cuadrado,df,<span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb186-2"><a href="bivariado-con-variables-categoricas.html#cb186-2" tabindex="-1"></a>valor_p</span></code></pre></div>
<pre><code>## [1] 8.304301e-20</code></pre>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="bivariado-con-variables-categoricas.html#cb188-1" tabindex="-1"></a><span class="fu">chisq.test</span>(observados)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  observados
## X-squared = 87.87, df = 2, p-value &lt; 2.2e-16</code></pre>
<p>Existe evidencia estadísticamente significativa para rechazar la hipótesis nula , esto significa que el tipo de medio de contacto influye significativamente en la probabilidad de que el cliente esté interesado en el depósito a plazo fijo.
Es decir, la respuesta del cliente varía según el canal de comunicación utilizado.</p>
<p><strong>TABLA POUTCOME vs Y</strong></p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="bivariado-con-variables-categoricas.html#cb190-1" tabindex="-1"></a>observados <span class="ot">&lt;-</span> <span class="fu">table</span>(bd<span class="sc">$</span>poutcome, bd<span class="sc">$</span>y)</span>
<span id="cb190-2"><a href="bivariado-con-variables-categoricas.html#cb190-2" tabindex="-1"></a>observados</span></code></pre></div>
<pre><code>##          
##             no  yes
##   failure  427   63
##   other    159   38
##   success   46   83
##   unknown 3368  337</code></pre>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="bivariado-con-variables-categoricas.html#cb192-1" tabindex="-1"></a>filas_totales <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(observados)</span>
<span id="cb192-2"><a href="bivariado-con-variables-categoricas.html#cb192-2" tabindex="-1"></a>col_totales <span class="ot">&lt;-</span> <span class="fu">colSums</span>(observados)</span>
<span id="cb192-3"><a href="bivariado-con-variables-categoricas.html#cb192-3" tabindex="-1"></a>total_general <span class="ot">&lt;-</span> <span class="fu">sum</span>(observados)</span>
<span id="cb192-4"><a href="bivariado-con-variables-categoricas.html#cb192-4" tabindex="-1"></a></span>
<span id="cb192-5"><a href="bivariado-con-variables-categoricas.html#cb192-5" tabindex="-1"></a>esperados <span class="ot">&lt;-</span> <span class="fu">outer</span>(filas_totales, col_totales, <span class="at">FUN =</span> <span class="cf">function</span>(f,c) f<span class="sc">*</span>c <span class="sc">/</span> total_general)</span>
<span id="cb192-6"><a href="bivariado-con-variables-categoricas.html#cb192-6" tabindex="-1"></a><span class="fu">dimnames</span>(esperados) <span class="ot">&lt;-</span> <span class="fu">dimnames</span>(observados)</span>
<span id="cb192-7"><a href="bivariado-con-variables-categoricas.html#cb192-7" tabindex="-1"></a>esperados</span></code></pre></div>
<pre><code>##          
##                  no       yes
##   failure  433.5324  56.46760
##   other    174.2977  22.70228
##   success  114.1340  14.86596
##   unknown 3278.0358 426.96417</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="bivariado-con-variables-categoricas.html#cb194-1" tabindex="-1"></a>chi_cuadrado <span class="ot">&lt;-</span> <span class="fu">sum</span>((observados <span class="sc">-</span> esperados)<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> esperados)</span>
<span id="cb194-2"><a href="bivariado-con-variables-categoricas.html#cb194-2" tabindex="-1"></a>chi_cuadrado</span></code></pre></div>
<pre><code>## [1] 386.8774</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="bivariado-con-variables-categoricas.html#cb196-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> (<span class="fu">nrow</span>(observados)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">*</span>(<span class="fu">ncol</span>(observados)<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb196-2"><a href="bivariado-con-variables-categoricas.html#cb196-2" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="bivariado-con-variables-categoricas.html#cb198-1" tabindex="-1"></a>alfa <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb198-2"><a href="bivariado-con-variables-categoricas.html#cb198-2" tabindex="-1"></a>valor_critico <span class="ot">&lt;-</span> <span class="fu">qchisq</span>(<span class="dv">1</span><span class="sc">-</span>alfa,df)</span>
<span id="cb198-3"><a href="bivariado-con-variables-categoricas.html#cb198-3" tabindex="-1"></a>valor_critico</span></code></pre></div>
<pre><code>## [1] 7.814728</code></pre>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="bivariado-con-variables-categoricas.html#cb200-1" tabindex="-1"></a>rechaza_H0 <span class="ot">&lt;-</span> chi_cuadrado <span class="sc">&gt;</span> valor_critico</span>
<span id="cb200-2"><a href="bivariado-con-variables-categoricas.html#cb200-2" tabindex="-1"></a>rechaza_H0</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="bivariado-con-variables-categoricas.html#cb202-1" tabindex="-1"></a><span class="cf">if</span> (rechaza_H0) {</span>
<span id="cb202-2"><a href="bivariado-con-variables-categoricas.html#cb202-2" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</span></span>
<span id="cb202-3"><a href="bivariado-con-variables-categoricas.html#cb202-3" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb202-4"><a href="bivariado-con-variables-categoricas.html#cb202-4" tabindex="-1"></a>  conclusion <span class="ot">&lt;-</span> <span class="st">&quot;Como chi_cuadrado es menor que el valor crítico, aceptamos H0.&quot;</span></span>
<span id="cb202-5"><a href="bivariado-con-variables-categoricas.html#cb202-5" tabindex="-1"></a>}</span>
<span id="cb202-6"><a href="bivariado-con-variables-categoricas.html#cb202-6" tabindex="-1"></a>conclusion</span></code></pre></div>
<pre><code>## [1] &quot;Como chi_cuadrado es mayor que el valor crítico, rechazamos H0.&quot;</code></pre>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="bivariado-con-variables-categoricas.html#cb204-1" tabindex="-1"></a>valor_p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(chi_cuadrado,df,<span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb204-2"><a href="bivariado-con-variables-categoricas.html#cb204-2" tabindex="-1"></a>valor_p</span></code></pre></div>
<pre><code>## [1] 1.539883e-83</code></pre>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="bivariado-con-variables-categoricas.html#cb206-1" tabindex="-1"></a><span class="fu">chisq.test</span>(observados)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  observados
## X-squared = 386.88, df = 3, p-value &lt; 2.2e-16</code></pre>
<p>Se rechaza la hipótesis nula, lo que indica que existe una relación muy fuerte entre el resultado de la campaña anterior y el interés actual del cliente.
En particular, los clientes cuyo resultado previo fue “success” muestran una probabilidad mucho mayor de aceptar la oferta nuevamente, lo que evidencia un patrón de comportamiento repetitivo positivo.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="análisis-exploratorio-bivariado.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referencias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/03-Parejo.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["mi-libro.pdf", "mi-libro.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
