<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 #Comienzo del EDA | Juan Marin, Santiago Hurtado, Andres Parejo</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 #Comienzo del EDA | Juan Marin, Santiago Hurtado, Andres Parejo" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 #Comienzo del EDA | Juan Marin, Santiago Hurtado, Andres Parejo" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Yihui Xie" />


<meta name="date" content="2025-08-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="diagrama-de-boxplot-para-campaign.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="comienzo-del-eda.html"><a href="comienzo-del-eda.html"><i class="fa fa-check"></i><b>3</b> #Comienzo del EDA</a></li>
<li class="chapter" data-level="4" data-path="diagrama-de-boxplot-para-campaign.html"><a href="diagrama-de-boxplot-para-campaign.html"><i class="fa fa-check"></i><b>4</b> Diagrama de boxplot para campaign</a></li>
<li class="chapter" data-level="5" data-path="diagrama-de-boxplot-para-pdays.html"><a href="diagrama-de-boxplot-para-pdays.html"><i class="fa fa-check"></i><b>5</b> Diagrama de boxplot para pdays</a></li>
<li class="chapter" data-level="6" data-path="Marin.html"><a href="#an%C3%A1lisis-exploratorio-bivariado."><i class="fa fa-check"></i><b>6</b> Análisis exploratorio bivariado.</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Juan Marin, Santiago Hurtado, Andres Parejo</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="comienzo-del-eda" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> #Comienzo del EDA<a href="comienzo-del-eda.html#comienzo-del-eda" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<blockquote>
<blockquote>
<blockquote>
<blockquote>
<blockquote>
<blockquote>
<blockquote>
<p>a01e76bbe664f91b922facc674643ce679eb29f3</p>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
</blockquote>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="comienzo-del-eda.html#cb5-1" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;bank.csv&quot;</span>,<span class="at">sep=</span><span class="st">&quot;;&quot;</span>)</span>
<span id="cb5-2"><a href="comienzo-del-eda.html#cb5-2" tabindex="-1"></a><span class="fu">head</span>(datos, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   age         job marital education default balance housing loan  contact day
## 1  30  unemployed married   primary      no    1787      no   no cellular  19
## 2  33    services married secondary      no    4789     yes  yes cellular  11
## 3  35  management  single  tertiary      no    1350     yes   no cellular  16
## 4  30  management married  tertiary      no    1476     yes  yes  unknown   3
## 5  59 blue-collar married secondary      no       0     yes   no  unknown   5
##   month duration campaign pdays previous poutcome  y
## 1   oct       79        1    -1        0  unknown no
## 2   may      220        1   339        4  failure no
## 3   apr      185        1   330        1  failure no
## 4   jun      199        4    -1        0  unknown no
## 5   may      226        1    -1        0  unknown no</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="comienzo-del-eda.html#cb7-1" tabindex="-1"></a><span class="fu">dim</span>(datos)</span></code></pre></div>
<pre><code>## [1] 4521   17</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="comienzo-del-eda.html#cb9-1" tabindex="-1"></a><span class="fu">colnames</span>(datos)</span></code></pre></div>
<pre><code>##  [1] &quot;age&quot;       &quot;job&quot;       &quot;marital&quot;   &quot;education&quot; &quot;default&quot;   &quot;balance&quot;  
##  [7] &quot;housing&quot;   &quot;loan&quot;      &quot;contact&quot;   &quot;day&quot;       &quot;month&quot;     &quot;duration&quot; 
## [13] &quot;campaign&quot;  &quot;pdays&quot;     &quot;previous&quot;  &quot;poutcome&quot;  &quot;y&quot;</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="comienzo-del-eda.html#cb11-1" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    4521 obs. of  17 variables:
##  $ age      : int  30 33 35 30 59 35 36 39 41 43 ...
##  $ job      : chr  &quot;unemployed&quot; &quot;services&quot; &quot;management&quot; &quot;management&quot; ...
##  $ marital  : chr  &quot;married&quot; &quot;married&quot; &quot;single&quot; &quot;married&quot; ...
##  $ education: chr  &quot;primary&quot; &quot;secondary&quot; &quot;tertiary&quot; &quot;tertiary&quot; ...
##  $ default  : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...
##  $ balance  : int  1787 4789 1350 1476 0 747 307 147 221 -88 ...
##  $ housing  : chr  &quot;no&quot; &quot;yes&quot; &quot;yes&quot; &quot;yes&quot; ...
##  $ loan     : chr  &quot;no&quot; &quot;yes&quot; &quot;no&quot; &quot;yes&quot; ...
##  $ contact  : chr  &quot;cellular&quot; &quot;cellular&quot; &quot;cellular&quot; &quot;unknown&quot; ...
##  $ day      : int  19 11 16 3 5 23 14 6 14 17 ...
##  $ month    : chr  &quot;oct&quot; &quot;may&quot; &quot;apr&quot; &quot;jun&quot; ...
##  $ duration : int  79 220 185 199 226 141 341 151 57 313 ...
##  $ campaign : int  1 1 1 4 1 2 1 2 2 1 ...
##  $ pdays    : int  -1 339 330 -1 -1 176 330 -1 -1 147 ...
##  $ previous : int  0 4 1 0 0 3 2 0 0 2 ...
##  $ poutcome : chr  &quot;unknown&quot; &quot;failure&quot; &quot;failure&quot; &quot;unknown&quot; ...
##  $ y        : chr  &quot;no&quot; &quot;no&quot; &quot;no&quot; &quot;no&quot; ...</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="comienzo-del-eda.html#cb13-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.0     ✔ stringr   1.5.1
## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ✔ purrr     1.1.0     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="comienzo-del-eda.html#cb15-1" tabindex="-1"></a> datos <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="comienzo-del-eda.html#cb15-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>day, <span class="sc">-</span>month, <span class="sc">-</span>previous) <span class="ot">-&gt;</span> df</span>
<span id="cb15-3"><a href="comienzo-del-eda.html#cb15-3" tabindex="-1"></a>  <span class="fu">head</span>(df, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   age         job marital education default balance housing loan  contact
## 1  30  unemployed married   primary      no    1787      no   no cellular
## 2  33    services married secondary      no    4789     yes  yes cellular
## 3  35  management  single  tertiary      no    1350     yes   no cellular
## 4  30  management married  tertiary      no    1476     yes  yes  unknown
## 5  59 blue-collar married secondary      no       0     yes   no  unknown
##   duration campaign pdays poutcome  y
## 1       79        1    -1  unknown no
## 2      220        1   339  failure no
## 3      185        1   330  failure no
## 4      199        4    -1  unknown no
## 5      226        1    -1  unknown no</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="comienzo-del-eda.html#cb17-1" tabindex="-1"></a>  df <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="comienzo-del-eda.html#cb17-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(),<span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_age NA_job NA_marital NA_education NA_default NA_balance NA_housing
## 1      0      0          0            0          0          0          0
##   NA_loan NA_contact NA_duration NA_campaign NA_pdays NA_poutcome NA_y
## 1       0          0           0           0        0           0    0</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="comienzo-del-eda.html#cb19-1" tabindex="-1"></a>  tabla_y <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="comienzo-del-eda.html#cb19-2" tabindex="-1"></a>  <span class="fu">count</span>(y, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="comienzo-del-eda.html#cb19-3" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia<span class="sc">/</span><span class="fu">sum</span>(Frecuencia)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>),</span>
<span id="cb19-4"><a href="comienzo-del-eda.html#cb19-4" tabindex="-1"></a>    <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb19-5"><a href="comienzo-del-eda.html#cb19-5" tabindex="-1"></a>  tabla_y <span class="sc">%&gt;%</span> </span>
<span id="cb19-6"><a href="comienzo-del-eda.html#cb19-6" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(y), <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb19-7"><a href="comienzo-del-eda.html#cb19-7" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;purple&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="comienzo-del-eda.html#cb19-8" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb19-9"><a href="comienzo-del-eda.html#cb19-9" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span> <span class="st">&quot;Distribucion interes de deposito a plazo fijo (no/yes)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb19-10"><a href="comienzo-del-eda.html#cb19-10" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb19-11"><a href="comienzo-del-eda.html#cb19-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Interes por el deposito a plazo fijo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Numero de clientes (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-12"><a href="comienzo-del-eda.html#cb19-12" tabindex="-1"></a>  <span class="co">#coord_flip() +</span></span>
<span id="cb19-13"><a href="comienzo-del-eda.html#cb19-13" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb19-14"><a href="comienzo-del-eda.html#cb19-14" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb19-15"><a href="comienzo-del-eda.html#cb19-15" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb19-16"><a href="comienzo-del-eda.html#cb19-16" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb19-17"><a href="comienzo-del-eda.html#cb19-17" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb19-18"><a href="comienzo-del-eda.html#cb19-18" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb19-19"><a href="comienzo-del-eda.html#cb19-19" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>)  </span>
<span id="cb19-20"><a href="comienzo-del-eda.html#cb19-20" tabindex="-1"></a>  ) </span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-2-1.png" width="672" />
#Analisis de la tabla y el grafico de barras de la variable “y” (objetivo)
En ambas representaciones visuales, se evidencia que existe una gran mayoria de los clientes, los cuales no estan interesados en hacer parte de la oferta de deposito a plazo fijo con un total de 4000 usuarios (88.55% de la muestra), asi mismo pues, la gran minoria de los encuestados dijo que si a dicha oferta siendo estos el 11.5% de las personas (521 en total). Estos marcadores indican el desbalance que se presenta en la variable objetivo, y que es de sumo cuidado tener en cuenta este desequilibrio para llevar a cabo los modelos predictivos.</p>
<p>#Tabla de las variables numericas independientes</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="comienzo-del-eda.html#cb20-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="comienzo-del-eda.html#cb20-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-3"><a href="comienzo-del-eda.html#cb20-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(age),</span>
<span id="cb20-4"><a href="comienzo-del-eda.html#cb20-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(age),</span>
<span id="cb20-5"><a href="comienzo-del-eda.html#cb20-5" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(age),</span>
<span id="cb20-6"><a href="comienzo-del-eda.html#cb20-6" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(age),</span>
<span id="cb20-7"><a href="comienzo-del-eda.html#cb20-7" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(age),</span>
<span id="cb20-8"><a href="comienzo-del-eda.html#cb20-8" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(age),</span>
<span id="cb20-9"><a href="comienzo-del-eda.html#cb20-9" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(age, <span class="fl">0.25</span>),</span>
<span id="cb20-10"><a href="comienzo-del-eda.html#cb20-10" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(age, <span class="fl">0.75</span>),</span>
<span id="cb20-11"><a href="comienzo-del-eda.html#cb20-11" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(age)) <span class="sc">%&gt;%</span></span>
<span id="cb20-12"><a href="comienzo-del-eda.html#cb20-12" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;age&quot;</span>) <span class="ot">-&gt;</span> variable_age</span>
<span id="cb20-13"><a href="comienzo-del-eda.html#cb20-13" tabindex="-1"></a></span>
<span id="cb20-14"><a href="comienzo-del-eda.html#cb20-14" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb20-15"><a href="comienzo-del-eda.html#cb20-15" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-16"><a href="comienzo-del-eda.html#cb20-16" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(balance),</span>
<span id="cb20-17"><a href="comienzo-del-eda.html#cb20-17" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(balance),</span>
<span id="cb20-18"><a href="comienzo-del-eda.html#cb20-18" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(balance),</span>
<span id="cb20-19"><a href="comienzo-del-eda.html#cb20-19" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(balance),</span>
<span id="cb20-20"><a href="comienzo-del-eda.html#cb20-20" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(balance),</span>
<span id="cb20-21"><a href="comienzo-del-eda.html#cb20-21" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(balance),</span>
<span id="cb20-22"><a href="comienzo-del-eda.html#cb20-22" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(balance, <span class="fl">0.25</span>),</span>
<span id="cb20-23"><a href="comienzo-del-eda.html#cb20-23" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(balance, <span class="fl">0.75</span>),</span>
<span id="cb20-24"><a href="comienzo-del-eda.html#cb20-24" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(balance)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-25"><a href="comienzo-del-eda.html#cb20-25" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;balance&quot;</span>) <span class="ot">-&gt;</span> variable_balance</span>
<span id="cb20-26"><a href="comienzo-del-eda.html#cb20-26" tabindex="-1"></a></span>
<span id="cb20-27"><a href="comienzo-del-eda.html#cb20-27" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb20-28"><a href="comienzo-del-eda.html#cb20-28" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-29"><a href="comienzo-del-eda.html#cb20-29" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(duration),</span>
<span id="cb20-30"><a href="comienzo-del-eda.html#cb20-30" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(duration),</span>
<span id="cb20-31"><a href="comienzo-del-eda.html#cb20-31" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(duration),</span>
<span id="cb20-32"><a href="comienzo-del-eda.html#cb20-32" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(duration),</span>
<span id="cb20-33"><a href="comienzo-del-eda.html#cb20-33" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(duration),</span>
<span id="cb20-34"><a href="comienzo-del-eda.html#cb20-34" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(duration),</span>
<span id="cb20-35"><a href="comienzo-del-eda.html#cb20-35" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(duration, <span class="fl">0.25</span>),</span>
<span id="cb20-36"><a href="comienzo-del-eda.html#cb20-36" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(duration, <span class="fl">0.75</span>),</span>
<span id="cb20-37"><a href="comienzo-del-eda.html#cb20-37" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(duration)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-38"><a href="comienzo-del-eda.html#cb20-38" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;duration&quot;</span>)<span class="ot">-&gt;</span> variable_duration</span>
<span id="cb20-39"><a href="comienzo-del-eda.html#cb20-39" tabindex="-1"></a></span>
<span id="cb20-40"><a href="comienzo-del-eda.html#cb20-40" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb20-41"><a href="comienzo-del-eda.html#cb20-41" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-42"><a href="comienzo-del-eda.html#cb20-42" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(campaign),</span>
<span id="cb20-43"><a href="comienzo-del-eda.html#cb20-43" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(campaign),</span>
<span id="cb20-44"><a href="comienzo-del-eda.html#cb20-44" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(campaign),</span>
<span id="cb20-45"><a href="comienzo-del-eda.html#cb20-45" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(campaign),</span>
<span id="cb20-46"><a href="comienzo-del-eda.html#cb20-46" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(campaign),</span>
<span id="cb20-47"><a href="comienzo-del-eda.html#cb20-47" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(campaign),</span>
<span id="cb20-48"><a href="comienzo-del-eda.html#cb20-48" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(campaign, <span class="fl">0.25</span>),</span>
<span id="cb20-49"><a href="comienzo-del-eda.html#cb20-49" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(campaign, <span class="fl">0.75</span>),</span>
<span id="cb20-50"><a href="comienzo-del-eda.html#cb20-50" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(campaign)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-51"><a href="comienzo-del-eda.html#cb20-51" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;campaign&quot;</span>)<span class="ot">-&gt;</span> variable_campaign</span>
<span id="cb20-52"><a href="comienzo-del-eda.html#cb20-52" tabindex="-1"></a></span>
<span id="cb20-53"><a href="comienzo-del-eda.html#cb20-53" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb20-54"><a href="comienzo-del-eda.html#cb20-54" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb20-55"><a href="comienzo-del-eda.html#cb20-55" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(pdays),</span>
<span id="cb20-56"><a href="comienzo-del-eda.html#cb20-56" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(pdays),</span>
<span id="cb20-57"><a href="comienzo-del-eda.html#cb20-57" tabindex="-1"></a>    <span class="at">desviacion =</span> <span class="fu">sd</span>(pdays),</span>
<span id="cb20-58"><a href="comienzo-del-eda.html#cb20-58" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(pdays),</span>
<span id="cb20-59"><a href="comienzo-del-eda.html#cb20-59" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(pdays),</span>
<span id="cb20-60"><a href="comienzo-del-eda.html#cb20-60" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(pdays),</span>
<span id="cb20-61"><a href="comienzo-del-eda.html#cb20-61" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(pdays, <span class="fl">0.25</span>),</span>
<span id="cb20-62"><a href="comienzo-del-eda.html#cb20-62" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(pdays, <span class="fl">0.75</span>),</span>
<span id="cb20-63"><a href="comienzo-del-eda.html#cb20-63" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(pdays)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-64"><a href="comienzo-del-eda.html#cb20-64" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;pdays&quot;</span>)<span class="ot">-&gt;</span> variable_pdays</span>
<span id="cb20-65"><a href="comienzo-del-eda.html#cb20-65" tabindex="-1"></a></span>
<span id="cb20-66"><a href="comienzo-del-eda.html#cb20-66" tabindex="-1"></a><span class="fu">bind_rows</span>(variable_age, variable_balance, variable_duration,variable_campaign,variable_pdays) <span class="sc">%&gt;%</span></span>
<span id="cb20-67"><a href="comienzo-del-eda.html#cb20-67" tabindex="-1"></a>  <span class="fu">select</span>(variable, <span class="fu">everything</span>())</span></code></pre></div>
<pre><code>##   variable    n      media  desviacion mediana minimo maximo  Q1   Q3  IQR
## 1      age 4521   41.17010   10.576211      39     19     87  33   49   16
## 2  balance 4521 1422.65782 3009.638142     444  -3313  71188  69 1480 1411
## 3 duration 4521  263.96129  259.856633     185      4   3025 104  329  225
## 4 campaign 4521    2.79363    3.109807       2      1     50   1    3    2
## 5    pdays 4521   39.76664  100.121124      -1     -1    871  -1   -1    0</code></pre>
<p>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD
# Interpretacion tabla
Por medio de un analisis estadistico, se evidencia un promedio de edad en los clientes del banco portugues de 41 años, con un rango que arranca desde los 19 años hasta los 87 como el dato maximo registrado, lo que muestra una poblacion adulta diversificada. El saldo promedio anual en las cuentas bancarias muestra una media de 1422 USD y una alta desviacion (Desviacion = 3009); además de unos valores extremos que abarcan saldos en numeros negativos como saldos bastante elevados (Maximo = 71188). Por otro lado, la duracion de las llamadas evidencia una media muestral de 264 segundos aproximadamente, y una desviacion considerable de 259 segundos; la mediana, es decir, el 50% de los datos es menor o igual a 185 segundos, y la duracion de estas llamadas esta comprendida en un intervalo que va desde los 4 segundos hasta los 3025, lo que simboliza una alta dispersion en los datos, y que por tanto puede derivar en sesgos.En relación con el número de contactos durante la campaña (campaign), se registra un promedio de 2,79 contactos (Desviacion = 3,11), con el 50 % de los casos por debajo de 2. Aunque se presentan valores extremos de hasta 50 contactos, la mayoría de los clientes fue contactada pocas veces, tal como refleja el rango intercuartílico comprendido entre los percentiles P25 y P75 (lo mismo que decir Q1 y Q3). A su vez, la variable pdays, que representa los días transcurridos desde el último contacto en campañas anteriores, muestra una media de 39,77 días (Desviacion = 100,12 días). Sin embargo, tanto la mediana como los percentiles P25 y P75 se encuentran en −1, lo que indica que la mayoría de los clientes no había sido contactada previamente. Aun así, existen registros que superan los 800 días, lo que evidencia comportamientos heterogéneos y la posible existencia de distintos segmentos dentro de la base de clientes.
#Graficos boxplot (caja y bigotes) de las variables numericas</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="comienzo-del-eda.html#cb22-1" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb22-2"><a href="comienzo-del-eda.html#cb22-2" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code></pre></div>
<pre><code>## 
## Adjuntando el paquete: &#39;gridExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     combine</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="comienzo-del-eda.html#cb25-1" tabindex="-1"></a><span class="co"># Boxplot de age</span></span>
<span id="cb25-2"><a href="comienzo-del-eda.html#cb25-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="comienzo-del-eda.html#cb25-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> age)) <span class="sc">+</span></span>
<span id="cb25-4"><a href="comienzo-del-eda.html#cb25-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#1f77b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href="comienzo-del-eda.html#cb25-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-6"><a href="comienzo-del-eda.html#cb25-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-7"><a href="comienzo-del-eda.html#cb25-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de la edad&quot;</span>,</span>
<span id="cb25-8"><a href="comienzo-del-eda.html#cb25-8" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Años&quot;</span>,</span>
<span id="cb25-9"><a href="comienzo-del-eda.html#cb25-9" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb25-10"><a href="comienzo-del-eda.html#cb25-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-11"><a href="comienzo-del-eda.html#cb25-11" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-4-1.png" width="672" />
#Interpretacion
El boxplot muestra que la mayoría de las edades se concentran entre 32 y 48 años, con una mediana cercana a 38 y un promedio ligeramente mayor, lo que indica una ligera asimetría hacia edades más altas. El rango total (sin contar atípicos) va de unos 22 a 72 años, y se observan varios outliers entre 72 y 90 años, lo que sugiere que, aunque la distribución es relativamente compacta, existen casos aislados de personas considerablemente mayores.
# Boxplot de balance</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="comienzo-del-eda.html#cb26-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="comienzo-del-eda.html#cb26-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> balance)) <span class="sc">+</span></span>
<span id="cb26-3"><a href="comienzo-del-eda.html#cb26-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#2f43b1&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="comienzo-del-eda.html#cb26-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb26-5"><a href="comienzo-del-eda.html#cb26-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-6"><a href="comienzo-del-eda.html#cb26-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución del balance de la cuenta&quot;</span>,</span>
<span id="cb26-7"><a href="comienzo-del-eda.html#cb26-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Usd&quot;</span>,</span>
<span id="cb26-8"><a href="comienzo-del-eda.html#cb26-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb26-9"><a href="comienzo-del-eda.html#cb26-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-10"><a href="comienzo-del-eda.html#cb26-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-5-1.png" width="672" />
#Interpretacion
La distribución del balance de la cuenta muestra una fuerte asimetría positiva, con la mayoría de los saldos concentrados cerca de valores bajos y un gran número de valores atípicos que alcanzan hasta 71,188 USD. El balance promedio es de 1,422.66 USD (Desviacion = 3,009.64), mientras que la mediana es de solo 444 USD, lo que refleja que pocos clientes con saldos muy altos elevan el promedio. Además, se observan saldos negativos mínimos de -3,313 USD, lo que indica sobregiros o deudas, y un rango intercuartílico que va de 69 a 1,480 USD, confirmando que la mayoría de los clientes mantiene balances reducidos.</p>
<p><strong>Diagrama de boxplot para duration</strong></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="comienzo-del-eda.html#cb27-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="comienzo-del-eda.html#cb27-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> duration)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="comienzo-del-eda.html#cb27-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#2ca02c&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="comienzo-del-eda.html#cb27-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="comienzo-del-eda.html#cb27-5" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb27-6"><a href="comienzo-del-eda.html#cb27-6" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de la duración de llamada (duration)&quot;</span>,</span>
<span id="cb27-7"><a href="comienzo-del-eda.html#cb27-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Segundos&quot;</span>,</span>
<span id="cb27-8"><a href="comienzo-del-eda.html#cb27-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb27-9"><a href="comienzo-del-eda.html#cb27-9" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb27-10"><a href="comienzo-del-eda.html#cb27-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-6-1.png" width="672" />
#Interpretacion
La duración de las llamadas presenta una media de aproximadamente 264 segundos (Desviacion = 260), con una mediana de 185 segundos, lo que indica que la mayoría de las llamadas fueron relativamente cortas. El rango intercuartílico va de 104 a 329 segundos, reflejando que el 50 % central de las llamadas dura entre poco menos de 2 y alrededor de 5,5 minutos. Sin embargo, el boxplot revela una marcada asimetría positiva debido a la presencia de múltiples valores atípicos que alcanzan hasta 3025 segundos (más de 50 minutos), lo que sugiere que, aunque la mayoría de las interacciones fueron breves, existen casos puntuales de llamadas excepcionalmente largas.</p>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="diagrama-de-boxplot-para-campaign.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/Marin.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
